const Afrika = {
    "EG": {
        "name": "Egyiptom",
        "flag": "🇪🇬",
        "officialFlag": "https://flagcdn.com/w320/eg.png",
        "code": "EG",
        "continent": "Afrika",
        "callingCode": "+20",
        "area": "1,001,450 km²",
        "population": "104.3 millió",
        "language": "Arab",
        "capital": "Kairó",
        "currency": "Egyiptomi font (EGP)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=24.7%2C22.0%2C36.9%2C31.7&layer=mapnik",
        "osmRelationId": "1473847",
        "attractions": ["Gízai piramisok", "Luxor", "Abu Simbel", "Vörös-tenger", "Nílus", "Karnaki templom", "Királyok völgye", "Egyiptomi Múzeum (Kairó)", "Alexandria", "Szfinx"],
        "alt_spellings": ["Egypt", "EG", "Egyiptom"]
    },
    "ZA": {
        "name": "Dél-Afrika",
        "flag": "🇿🇦",
        "officialFlag": "https://flagcdn.com/w320/za.png",
        "code": "ZA",
        "continent": "Afrika",
        "callingCode": "+27",
        "area": "1,221,037 km²",
        "population": "60.4 millió",
        "language": "Afrikaans, Angol, Zulu",
        "capital": "Fokváros",
        "currency": "Rand (ZAR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=16.3%2C-34.8%2C32.9%2C-22.1&layer=mapnik",
        "osmRelationId": "142963",
        "attractions": ["Asztali-hegy", "Kruger Nemzeti Park", "Robben-sziget", "Garden Route", "Drakensberg", "Jóreménység foka", "Blyde River Canyon", "Stellenbosch borvidék", "Apartheid Múzeum", "Boulders Beach (pingvinek)"],
        "alt_spellings": ["South Africa", "RSA", "ZA", "Dél-Afrika"]
    },
     "KE": {
        "name": "Kenya",
        "flag": "🇰🇪",
        "officialFlag": "https://flagcdn.com/w320/ke.png",
        "code": "KE",
        "continent": "Afrika",
        "callingCode": "+254",
        "area": "580,367 km²",
        "population": "54.0 millió",
        "language": "Swahili, Angol",
        "capital": "Nairobi",
        "currency": "Kenyai shilling (KES)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=33.9%2C-4.7%2C41.9%2C5.5&layer=mapnik",
        "osmRelationId": "192798",
        "attractions": ["Masai Mara", "Kilimanjaro", "Amboseli", "Mombasa", "Nakuru-tó", "Tsavo Nemzeti Park", "Lamu-sziget", "Hell's Gate Nemzeti Park", "Diani Beach", "Nairobi Nemzeti Park"]
    },
    "NG": {
        "name": "Nigéria",
        "flag": "🇳🇬",
        "officialFlag": "https://flagcdn.com/w320/ng.png",
        "code": "NG",
        "continent": "Afrika",
        "callingCode": "+234",
        "area": "923,768 km²",
        "population": "218.5 millió",
        "language": "Angol",
        "capital": "Abuja",
        "currency": "Naira (NGN)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=2.7%2C4.3%2C14.7%2C13.9&layer=mapnik",
        "osmRelationId": "192787",
        "attractions": ["Lagos", "Yankari Nemzeti Park", "Osun-Osogbo", "Zuma Rock", "Cross River", "Lekki Conservation Centre", "Olumo Rock", "Aso Rock", "Nike Art Gallery", "Kainji Nemzeti Park"]
    },
    "MA": {
        "name": "Marokkó",
        "flag": "🇲🇦",
        "officialFlag": "https://flagcdn.com/w320/ma.png",
        "code": "MA",
        "continent": "Afrika",
        "callingCode": "+212",
        "area": "446,550 km²",
        "population": "37.5 millió",
        "language": "Arab, Berber",
        "capital": "Rabat",
        "currency": "Dirham (MAD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-17.0%2C21.4%2C-1.0%2C35.9&layer=mapnik",
        "osmRelationId": "3630439",
        "attractions": ["Marrakech", "Fez", "Casablanca", "Sahara", "Chefchaouen", "Djemaa el-Fna", "Ait Benhaddou", "Atlasz-hegység", "Essaouira", "Hassan II Mecset"]
    },
    "ET": {
        "name": "Etiópia",
        "flag": "🇪🇹",
        "officialFlag": "https://flagcdn.com/w320/et.png",
        "code": "ET",
        "continent": "Afrika",
        "callingCode": "+251",
        "area": "1,104,300 km²",
        "population": "117.9 millió",
        "language": "Amhara",
        "capital": "Addis Ababa",
        "currency": "Birr (ETB)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=32.9%2C3.4%2C47.8%2C14.9&layer=mapnik",
        "osmRelationId": "192800",
        "attractions": ["Lalibela", "Simien hegység", "Danakil sivatag", "Blue Nile Falls", "Harar", "Omo-völgy", "Aksum", "Gondar", "Tana-tó", "Erta Ale vulkán"]
    },
    "GH": {
        "name": "Ghána",
        "flag": "🇬🇭",
        "officialFlag": "https://flagcdn.com/w320/gh.png",
        "code": "GH",
        "continent": "Afrika",
        "callingCode": "+233",
        "area": "238,533 km²",
        "population": "32.8 millió",
        "language": "Angol",
        "capital": "Accra",
        "currency": "Cedi (GHS)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-3.3%2C4.7%2C1.2%2C11.2&layer=mapnik",
        "osmRelationId": "192781",
        "attractions": ["Cape Coast Castle", "Kakum Nemzeti Park", "Kumasi", "Mole Nemzeti Park", "Elmina", "Wli-vízesés", "Accra", "Boti-vízesés", "Nzulezo", "Labadi Beach"]
    },
    "TZ": {
        "name": "Tanzánia",
        "flag": "🇹🇿",
        "officialFlag": "https://flagcdn.com/w320/tz.png",
        "code": "TZ",
        "continent": "Afrika",
        "callingCode": "+255",
        "area": "947,303 km²",
        "population": "61.5 millió",
        "language": "Swahili, Angol",
        "capital": "Dodoma",
        "currency": "Shilling (TZS)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=29.3%2C-11.7%2C40.4%2C-0.9&layer=mapnik",
        "osmRelationId": "192796",
        "attractions": ["Serengeti", "Ngorongoro kráter", "Kilimanjaro", "Zanzibar", "Tarangire", "Selous Vadrezervátum", "Tanganyika-tó", "Ruaha Nemzeti Park", "Mafia-sziget", "Olduvai-szurdok"]
    },
    "UG": {
        "name": "Uganda",
        "flag": "🇺🇬",
        "officialFlag": "https://flagcdn.com/w320/ug.png",
        "code": "UG",
        "continent": "Afrika",
        "callingCode": "+256",
        "area": "241,038 km²",
        "population": "47.1 millió",
        "language": "Angol, Swahili",
        "capital": "Kampala",
        "currency": "Shilling (UGX)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=29.6%2C-1.5%2C35.0%2C4.2&layer=mapnik",
        "osmRelationId": "192796",
        "attractions": ["Bwindi", "Queen Elizabeth Park", "Murchison Falls", "Viktória-tó", "Rwenzori hegység", "Jinja (Nílus forrása)", "Kibale Nemzeti Park", "Sipi-vízesés", "Bunyonyi-tó", "Kidepo Valley Nemzeti Park"]
    },
    "DZ": {
        "name": "Algéria",
        "flag": "🇩🇿",
        "officialFlag": "https://flagcdn.com/w320/dz.png",
        "code": "DZ",
        "continent": "Afrika",
        "callingCode": "+213",
        "area": "2,381,741 km²",
        "population": "44.9 millió",
        "language": "Arab, Berber",
        "capital": "Algír",
        "currency": "Dinár (DZD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-8.7%2C19.0%2C12.0%2C37.1&layer=mapnik",
        "osmRelationId": "192756",
        "attractions": ["Sahara sivatag", "Tassili n'Ajjer", "Algír Kasbah", "Timgad", "Djémila", "Hoggar-hegység", "Ghardaïa", "Constantine", "Tipaza", "Oran"]
    },
    "AO": {
        "name": "Angola",
        "flag": "🇦🇴",
        "officialFlag": "https://flagcdn.com/w320/ao.png",
        "code": "AO",
        "continent": "Afrika",
        "callingCode": "+244",
        "area": "1,246,700 km²",
        "population": "33.9 millió",
        "language": "Portugál",
        "capital": "Luanda",
        "currency": "Kwanza (AOA)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=11.7%2C-18.0%2C24.1%2C-4.4&layer=mapnik",
        "osmRelationId": "195267",
        "attractions": ["Kalandula vízesés", "Kissama Nemzeti Park", "Benguela", "Namibe sivatag", "Luanda", "Tundavala hasadék", "Fekete sziklák (Pungo Andongo)", "Miradouro da Lua", "Iona Nemzeti Park", "Mussulo-sziget"]
    },
    "MZ": {
        "name": "Mozambik",
        "flag": "🇲🇿",
        "officialFlag": "https://flagcdn.com/w320/mz.png",
        "code": "MZ",
        "continent": "Afrika",
        "callingCode": "+258",
        "area": "801,590 km²",
        "population": "32.2 millió",
        "language": "Portugál",
        "capital": "Maputo",
        "currency": "Metical (MZN)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=30.2%2C-26.9%2C40.8%2C-10.5&layer=mapnik",
        "osmRelationId": "195273",
        "attractions": ["Bazaruto szigetek", "Gorongosa", "Ilha de Moçambique", "Tofo Beach", "Maputo", "Quirimbas szigetcsoport", "Niassa Vadrezervátum", "Ponta do Ouro", "Vilanculos", "Inhaca-sziget"]
    },
    "MG": {
        "name": "Madagaszkár",
        "flag": "🇲🇬",
        "officialFlag": "https://flagcdn.com/w320/mg.png",
        "code": "MG",
        "continent": "Afrika",
        "callingCode": "+261",
        "area": "587,041 km²",
        "population": "28.4 millió",
        "language": "Malagasy, Francia",
        "capital": "Antananarivo",
        "currency": "Ariary (MGA)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=43.2%2C-25.6%2C50.5%2C-11.9&layer=mapnik",
        "osmRelationId": "403823",
        "attractions": ["Baobab Avenue", "Andasibe-Mantadia", "Tsingy de Bemaraha", "Nosy Be", "Isalo", "Ranomafana Nemzeti Park", "Királydomb (Ambohimanga)", "Île Sainte-Marie", "Ifaty", "Masoala Nemzeti Park"]
    },
    "CM": {
        "name": "Kamerun",
        "flag": "🇨🇲",
        "officialFlag": "https://flagcdn.com/w320/cm.png",
        "code": "CM",
        "continent": "Afrika",
        "callingCode": "+237",
        "area": "475,442 km²",
        "population": "27.2 millió",
        "language": "Francia, Angol",
        "capital": "Yaoundé",
        "currency": "CFA frank (XAF)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=8.5%2C1.7%2C16.2%2C13.1&layer=mapnik",
        "osmRelationId": "192774",
        "attractions": ["Waza Nemzeti Park", "Dja Faunal Reserve", "Limbe", "Foumban", "Kribi", "Kamerun-hegy", "Lobéké Nemzeti Park", "Ekom-Nkam vízesés", "Korup Nemzeti Park", "Yaoundé"]
    },
    "CI": {
        "name": "Elefántcsontpart",
        "flag": "🇨🇮",
        "officialFlag": "https://flagcdn.com/w320/ci.png",
        "code": "CI",
        "continent": "Afrika",
        "callingCode": "+225",
        "area": "322,463 km²",
        "population": "27.5 millió",
        "language": "Francia",
        "capital": "Yamoussoukro",
        "currency": "CFA frank (XOF)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-8.6%2C4.4%2C-2.5%2C10.7&layer=mapnik",
        "osmRelationId": "192779",
        "attractions": ["Abidjan", "Taï Nemzeti Park", "Grand-Bassam", "Yamoussoukro Bazilika", "Assinie", "Comoé Nemzeti Park", "Man", "Sassandra", "La Cascade vízesés", "Parc du Banco"]
    },
    "ZM": {
        "name": "Zambia",
        "flag": "🇿🇲",
        "officialFlag": "https://flagcdn.com/w320/zm.png",
        "code": "ZM",
        "continent": "Afrika",
        "callingCode": "+260",
        "area": "752,618 km²",
        "population": "18.9 millió",
        "language": "Angol",
        "capital": "Lusaka",
        "currency": "Kwacha (ZMW)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=21.9%2C-18.1%2C33.7%2C-8.2&layer=mapnik",
        "osmRelationId": "195271",
        "attractions": ["Viktória-vízesés", "South Luangwa", "Kafue Nemzeti Park", "Lake Kariba", "Lusaka", "Lower Zambezi Nemzeti Park", "Devil's Pool", "Tanganyika-tó", "Bangweulu-mocsár", "Livingstone"]
    },
    "ZW": {
        "name": "Zimbabwe",
        "flag": "🇿🇼",
        "officialFlag": "https://flagcdn.com/w320/zw.png",
        "code": "ZW",
        "continent": "Afrika",
        "callingCode": "+263",
        "area": "390,757 km²",
        "population": "15.1 millió",
        "language": "Angol, Shona",
        "capital": "Harare",
        "currency": "Dollár (USD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=25.2%2C-22.4%2C33.1%2C-15.6&layer=mapnik",
        "osmRelationId": "195272",
        "attractions": ["Viktória-vízesés", "Great Zimbabwe", "Hwange Nemzeti Park", "Matobo Hills", "Harare", "Mana Pools Nemzeti Park", "Kariba-tó", "Keleti-felföld", "Chinhoyi-barlangok", "Bulawayo"]
    },
    "BW": {
        "name": "Botswana",
        "flag": "🇧🇼",
        "officialFlag": "https://flagcdn.com/w320/bw.png",
        "code": "BW",
        "continent": "Afrika",
        "callingCode": "+267",
        "area": "581,730 km²",
        "population": "2.4 millió",
        "language": "Angol, Setswana",
        "capital": "Gaborone",
        "currency": "Pula (BWP)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=19.9%2C-26.9%2C29.4%2C-17.8&layer=mapnik",
        "osmRelationId": "195270",
        "attractions": ["Okavango Delta", "Chobe Nemzeti Park", "Kalahari sivatag", "Makgadikgadi", "Gaborone", "Moremi Vadrezervátum", "Tsodilo-hegy", "Khama Rhino Sanctuary", "Nxai Pan Nemzeti Park", "Three Dikgosi Monument"]
    },
    "NA": {
        "name": "Namíbia",
        "flag": "🇳🇦",
        "officialFlag": "https://flagcdn.com/w320/na.png",
        "code": "NA",
        "continent": "Afrika",
        "callingCode": "+264",
        "area": "825,615 km²",
        "population": "2.5 millió",
        "language": "Angol",
        "capital": "Windhoek",
        "currency": "Dollár (NAD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=11.7%2C-29.0%2C25.3%2C-16.9&layer=mapnik",
        "osmRelationId": "195266",
        "attractions": ["Namib sivatag", "Etosha Nemzeti Park", "Sossusvlei", "Skeleton Coast", "Fish River Canyon", "Deadvlei", "Twyfelfontein", "Swakopmund", "Cape Cross", "Kolmanskop"]
    },
    "RW": {
        "name": "Ruanda",
        "flag": "🇷🇼",
        "officialFlag": "https://flagcdn.com/w320/rw.png",
        "code": "RW",
        "continent": "Afrika",
        "callingCode": "+250",
        "area": "26,338 km²",
        "population": "13.3 millió",
        "language": "Kinyarwanda, Francia, Angol",
        "capital": "Kigali",
        "currency": "Frank (RWF)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=28.9%2C-2.8%2C30.9%2C-1.0&layer=mapnik",
        "osmRelationId": "194252",
        "attractions": ["Volcanoes Nemzeti Park", "Nyungwe Forest", "Kivu-tó", "Kigali", "Akagera", "Kigali Genocide Memorial", "Dian Fossey sírja", "King's Palace Museum", "Gishwati Mukura Nemzeti Park", "Musanze-barlangok"]
    },
    "TN": {
        "name": "Tunézia",
        "flag": "🇹🇳",
        "officialFlag": "https://flagcdn.com/w320/tn.png",
        "code": "TN",
        "continent": "Afrika",
        "callingCode": "+216",
        "area": "163,610 km²",
        "population": "11.9 millió",
        "language": "Arab",
        "capital": "Tunis",
        "currency": "Dinár (TND)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=7.5%2C30.2%2C11.6%2C37.5&layer=mapnik",
        "osmRelationId": "192757",
        "attractions": ["Karthágó", "Sidi Bou Said", "El Djem", "Sahara", "Tunis medina", "Bardo Múzeum", "Djerba sziget", "Dougga", "Kairouan", "Matmata"]
    },
};