const America = {     
    "US": {
        "name": "Amerikai Egyesült Államok",
        "flag": "🇺🇸",
        "officialFlag": "https://flagcdn.com/w320/us.png",
        "code": "US",
        "continent": "Észak-Amerika",
        "callingCode": "+1",
        "area": "9,833,517 km²",
        "population": "331.9 millió",
        "language": "Angol",
        "capital": "Washington D.C.",
        "currency": "Dollár (USD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-125.0%2C25.0%2C-66.9%2C49.4&layer=mapnik",
        "osmRelationId": "148838",
        "attractions": ["Szabadság-szobor", "Grand Canyon", "Yellowstone", "Times Square", "Golden Gate híd", "Fehér Ház", "Las Vegas Strip", "Walt Disney World", "Yosemite Nemzeti Park", "Hawaii"],
        "alt_spellings": ["United States", "USA", "US", "Amerikai Egyesült Államok"]
    },
    "CA": {
        "name": "Kanada",
        "flag": "🇨🇦",
        "officialFlag": "https://flagcdn.com/w320/ca.png",
        "code": "CA",
        "continent": "Észak-Amerika",
        "callingCode": "+1",
        "area": "9,984,670 km²",
        "population": "38.2 millió",
        "language": "Angol, Francia",
        "capital": "Ottawa",
        "currency": "Kanadai dollár (CAD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-141.0%2C41.7%2C-52.6%2C83.1&layer=mapnik",
        "osmRelationId": "1428125",
        "attractions": ["Niagara-vízesés", "Banff Nemzeti Park", "CN Tower", "Quebec óvárosa", "Rocky Mountains", "Jasper Nemzeti Park", "Vancouver", "Moraine-tó", "Montreal", "Prince Edward-sziget"],
        "alt_spellings": ["Canada", "CA", "Kanada"]
    },
    "BR": {
        "name": "Brazília",
        "flag": "🇧🇷",
        "officialFlag": "https://flagcdn.com/w320/br.png",
        "code": "BR",
        "continent": "Dél-Amerika",
        "callingCode": "+55",
        "area": "8,514,877 km²",
        "population": "215.3 millió",
        "language": "Portugál",
        "capital": "Brasília",
        "currency": "Real (BRL)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-73.9%2C-33.7%2C-34.8%2C5.3&layer=mapnik",
        "osmRelationId": "59470",
        "attractions": ["Krisztus-szobor", "Copacabana", "Iguazu-vízesés", "Amazonas", "Sugarloaf hegy", "Karnevál (Rio)", "Salvador", "Pantanal", "Lençóis Maranhenses Nemzeti Park", "Fernando de Noronha"],
        "alt_spellings": ["Brazil", "Brasil", "BR", "Brazília"]
    },
    "AR": {
        "name": "Argentína",
        "flag": "🇦🇷",
        "officialFlag": "https://flagcdn.com/w320/ar.png",
        "code": "AR",
        "continent": "Dél-Amerika",
        "callingCode": "+54",
        "area": "2,780,400 km²",
        "population": "45.4 millió",
        "language": "Spanyol",
        "capital": "Buenos Aires",
        "currency": "Argentin peso (ARS)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-73.6%2C-55.1%2C-53.6%2C-21.8&layer=mapnik",
        "osmRelationId": "286393",
        "attractions": ["Buenos Aires", "Iguazu-vízesés", "Patagónia", "Mendoza", "Ushuaia", "Perito Moreno-gleccser", "La Boca", "Bariloche", "Salta", "Tierra del Fuego Nemzeti Park"],
        "alt_spellings": ["Argentina", "AR", "Argentína"]
    },
    "MX": {
        "name": "Mexikó",
        "flag": "🇲🇽",
        "officialFlag": "https://flagcdn.com/w320/mx.png",
        "code": "MX",
        "continent": "Észak-Amerika",
        "callingCode": "+52",
        "area": "1,964,375 km²",
        "population": "128.9 millió",
        "language": "Spanyol",
        "capital": "Mexikóváros",
        "currency": "Mexikói peso (MXN)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-117.1%2C14.5%2C-86.7%2C32.7&layer=mapnik",
        "osmRelationId": "114686",
        "attractions": ["Chichen Itza", "Teotihuacan", "Cancún", "Tulum", "Frida Kahlo múzeum", "Palenque", "Cabo San Lucas", "Oaxaca", "Copper Canyon", "Holtak napja ünnepségek"]
    },
    "GT": {
        "name": "Guatemala",
        "flag": "🇬🇹",
        "officialFlag": "https://flagcdn.com/w320/gt.png",
        "code": "GT",
        "continent": "Közép-Amerika",
        "callingCode": "+502",
        "area": "108,889 km²",
        "population": "17.9 millió",
        "language": "Spanyol",
        "capital": "Guatemala City",
        "currency": "Quetzal (GTQ)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-92.2%2C13.7%2C-88.2%2C17.8&layer=mapnik",
        "osmRelationId": "287933",
        "attractions": ["Tikal", "Antigua Guatemala", "Atitlán-tó", "Semuc Champey", "Yaxha", "Pacaya vulkán", "Chichicastenango piac", "Flores", "Rio Dulce", "El Mirador"]
    },
    "BZ": {
        "name": "Belize",
        "flag": "🇧🇿",
        "officialFlag": "https://flagcdn.com/w320/bz.png",
        "code": "BZ",
        "continent": "Közép-Amerika",
        "callingCode": "+501",
        "area": "22,966 km²",
        "population": "0.4 millió",
        "language": "Angol",
        "capital": "Belmopan",
        "currency": "Belize dollár (BZD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-89.2%2C15.9%2C-87.8%2C18.5&layer=mapnik",
        "osmRelationId": "287827",
        "attractions": ["Nagy Kék Lyuk", "Caracol", "Belize-i korallzátony", "Xunantunich", "Hol Chan", "Caye Caulker", "Actun Tunichil Muknal barlang", "Lamanai", "Ambergris Caye", "Glover's Reef Atoll"]
    },
    "SV": {
        "name": "El Salvador",
        "flag": "🇸🇻",
        "officialFlag": "https://flagcdn.com/w320/sv.png",
        "code": "SV",
        "continent": "Közép-Amerika",
        "callingCode": "+503",
        "area": "21,041 km²",
        "population": "6.5 millió",
        "language": "Spanyol",
        "capital": "San Salvador",
        "currency": "Dollár (USD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-90.1%2C13.1%2C-87.7%2C14.4&layer=mapnik",
        "osmRelationId": "287828",
        "attractions": ["Joya de Cerén", "Tazumal", "Santa Ana vulkán", "Suchitoto", "El Tunco", "Ruta de las Flores", "Coatepeque-tó", "El Boquerón Nemzeti Park", "San Andrés", "La Palma"]
    },
    "HN": {
        "name": "Honduras",
        "flag": "🇭🇳",
        "officialFlag": "https://flagcdn.com/w320/hn.png",
        "code": "HN",
        "continent": "Közép-Amerika",
        "callingCode": "+504",
        "area": "112,492 km²",
        "population": "10.0 millió",
        "language": "Spanyol",
        "capital": "Tegucigalpa",
        "currency": "Lempira (HNL)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-89.4%2C12.9%2C-83.1%2C16.0&layer=mapnik",
        "osmRelationId": "287826",
        "attractions": ["Copán", "Roatán sziget", "La Tigra Nemzeti Park", "Utila", "Pico Bonito", "Cayos Cochinos", "Yojoa-tó", "Pulhapanzak-vízesés", "Comayagua", "Gracias"]
    },
    "NI": {
        "name": "Nicaragua",
        "flag": "🇳🇮",
        "officialFlag": "https://flagcdn.com/w320/ni.png",
        "code": "NI",
        "continent": "Közép-Amerika",
        "callingCode": "+505",
        "area": "130,373 km²",
        "population": "6.6 millió",
        "language": "Spanyol",
        "capital": "Managua",
        "currency": "Córdoba (NIO)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-87.7%2C10.7%2C-82.7%2C15.0&layer=mapnik",
        "osmRelationId": "287825",
        "attractions": ["Granada", "León", "Ometepe sziget", "Masaya vulkán", "San Juan del Sur", "Corn Islands", "Somoto-kanyon", "Apoyo lagúna", "Cerro Negro", "Solentiname-szigetek"]
    },
    "CR": {
        "name": "Costa Rica",
        "flag": "🇨🇷",
        "officialFlag": "https://flagcdn.com/w320/cr.png",
        "code": "CR",
        "continent": "Közép-Amerika",
        "callingCode": "+506",
        "area": "51,100 km²",
        "population": "5.1 millió",
        "language": "Spanyol",
        "capital": "San José",
        "currency": "Colón (CRC)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-85.9%2C8.0%2C-82.6%2C11.2&layer=mapnik",
        "osmRelationId": "287667",
        "attractions": ["Manuel Antonio", "Arenal vulkán", "Monteverde", "Tortuguero", "Tamarindo", "Corcovado Nemzeti Park", "La Fortuna-vízesés", "Poás vulkán", "La Paz vízeséskertek", "Cahuita Nemzeti Park"]
    },
    "PA": {
        "name": "Panama",
        "flag": "🇵🇦",
        "officialFlag": "https://flagcdn.com/w320/pa.png",
        "code": "PA",
        "continent": "Közép-Amerika",
        "callingCode": "+507",
        "area": "75,417 km²",
        "population": "4.3 millió",
        "language": "Spanyol",
        "capital": "Panama City",
        "currency": "Balboa (PAB)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-83.0%2C7.2%2C-77.2%2C9.6&layer=mapnik",
        "osmRelationId": "287668",
        "attractions": ["Panama-csatorna", "Casco Viejo", "San Blas-szigetek", "Boquete", "Coiba Nemzeti Park", "Bocas del Toro", "Soberanía Nemzeti Park", "Pearl-szigetek", "El Valle de Antón", "Portobelo"]
    },
    "CU": {
        "name": "Kuba",
        "flag": "🇨🇺",
        "officialFlag": "https://flagcdn.com/w320/cu.png",
        "code": "CU",
        "continent": "Közép-Amerika",
        "callingCode": "+53",
        "area": "109,884 km²",
        "population": "11.3 millió",
        "language": "Spanyol",
        "capital": "Havanna",
        "currency": "Kubai peso (CUP)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-84.9%2C19.8%2C-74.1%2C23.3&layer=mapnik",
        "osmRelationId": "307833",
        "attractions": ["Havanna óvárosa", "Varadero", "Trinidad", "Viñales-völgy", "Santiago de Cuba", "Che Guevara Mauzóleum", "Cienfuegos", "El Capitolio", "Playa Paraíso", "Baracoa"]
    },
    "JM": {
        "name": "Jamaica",
        "flag": "🇯🇲",
        "officialFlag": "https://flagcdn.com/w320/jm.png",
        "code": "JM",
        "continent": "Közép-Amerika",
        "callingCode": "+1876",
        "area": "10,991 km²",
        "population": "2.9 millió",
        "language": "Angol",
        "capital": "Kingston",
        "currency": "Jamaica dollár (JMD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-78.4%2C17.7%2C-76.2%2C18.5&layer=mapnik",
        "osmRelationId": "307829",
        "attractions": ["Blue Mountains", "Negril", "Dunn's River Falls", "Bob Marley múzeum", "Montego Bay", "Rick's Café", "Seven Mile Beach", "Port Antonio", "Reach Falls", "Rose Hall Great House"]
    },
    "HT": {
        "name": "Haiti",
        "flag": "🇭🇹",
        "officialFlag": "https://flagcdn.com/w320/ht.png",
        "code": "HT",
        "continent": "Közép-Amerika",
        "callingCode": "+509",
        "area": "27,750 km²",
        "population": "11.4 millió",
        "language": "Francia, Kreol",
        "capital": "Port-au-Prince",
        "currency": "Gourde (HTG)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-74.5%2C18.0%2C-71.6%2C20.1&layer=mapnik",
        "osmRelationId": "307828",
        "attractions": ["Citadelle Laferrière", "Labadee", "Jacmel", "Cap-Haïtien", "Saut-d'Eau vízesés", "Sans-Souci palota", "Bassin Bleu", "Île-à-Vache", "Musée du Panthéon National Haïtien", "Gelee Beach"]
    },
    "DO": {
        "name": "Dominikai Köztársaság",
        "flag": "🇩🇴",
        "officialFlag": "https://flagcdn.com/w320/do.png",
        "code": "DO",
        "continent": "Közép-Amerika",
        "callingCode": "+1809",
        "area": "48,671 km²",
        "population": "10.8 millió",
        "language": "Spanyol",
        "capital": "Santo Domingo",
        "currency": "Peso (DOP)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-72.0%2C17.5%2C-68.3%2C19.9&layer=mapnik",
        "osmRelationId": "307827",
        "attractions": ["Punta Cana", "Santo Domingo óvárosa", "Saona sziget", "Los Haitises", "Amber Cove", "Samaná-félsziget", "27 Charcos de Damajagua", "Pico Duarte", "Bahia de las Aguilas", "Catalina-sziget"]
    },
    "PR": {
        "name": "Puerto Rico",
        "flag": "🇵🇷",
        "officialFlag": "https://flagcdn.com/w320/pr.png",
        "code": "PR",
        "continent": "Közép-Amerika",
        "callingCode": "+1787",
        "area": "9,104 km²",
        "population": "3.2 millió",
        "language": "Spanyol, Angol",
        "capital": "San Juan",
        "currency": "Dollár (USD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-67.9%2C17.9%2C-65.2%2C18.5&layer=mapnik",
        "osmRelationId": "4422614",
        "attractions": ["El Yunque", "Old San Juan", "Bioluminescent Bay", "Cueva Ventana", "Flamenco Beach", "Castillo San Felipe del Morro", "Vieques", "Toro Verde Adventure Park", "Camuy River Cave Park", "Rincón"]
    },
    "TT": {
        "name": "Trinidad és Tobago",
        "flag": "🇹🇹",
        "officialFlag": "https://flagcdn.com/w320/tt.png",
        "code": "TT",
        "continent": "Közép-Amerika",
        "callingCode": "+1868",
        "area": "5,128 km²",
        "population": "1.4 millió",
        "language": "Angol",
        "capital": "Port of Spain",
        "currency": "Trinidad dollár (TTD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-61.9%2C10.0%2C-60.5%2C11.3&layer=mapnik",
        "osmRelationId": "555984",
        "attractions": ["Carnival", "Maracas Bay", "Asa Wright", "Pitch Lake", "Tobago Cays", "Pigeon Point", "Englishman's Bay", "Caroni Madárrezervátum", "Fort King George", "Nylon Pool"]
    },
    "BB": {
        "name": "Barbados",
        "flag": "🇧🇧",
        "officialFlag": "https://flagcdn.com/w320/bb.png",
        "code": "BB",
        "continent": "Közép-Amerika",
        "callingCode": "+1246",
        "area": "430 km²",
        "population": "0.3 millió",
        "language": "Angol",
        "capital": "Bridgetown",
        "currency": "Barbados dollár (BBD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-59.7%2C13.0%2C-59.4%2C13.3&layer=mapnik",
        "osmRelationId": "396253",
        "attractions": ["Harrison's Cave", "Animal Flower Cave", "Bridgetown", "Crane Beach", "Mount Gay Rum", "Bathsheba Beach", "St. Nicholas Abbey", "Oistins Fish Fry", "Hunte's Gardens", "Carlisle Bay"]
    },
    "BS": {
        "name": "Bahama-szigetek",
        "flag": "🇧🇸",
        "officialFlag": "https://flagcdn.com/w320/bs.png",
        "code": "BS",
        "continent": "Közép-Amerika",
        "callingCode": "+1242",
        "area": "13,943 km²",
        "population": "0.4 millió",
        "language": "Angol",
        "capital": "Nassau",
        "currency": "Bahama dollár (BSD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-78.2%2C20.9%2C-72.7%2C27.3&layer=mapnik",
        "osmRelationId": "307844",
        "attractions": ["Paradise Island", "Exuma Cays", "Pink Sands Beach", "Atlantis Resort", "Swimming Pigs", "Dean's Blue Hole", "Harbour Island", "Lucayan Nemzeti Park", "Queen's Staircase", "Blue Lagoon Island"]
    },
    "CO": {
        "name": "Kolumbia",
        "flag": "🇨🇴",
        "officialFlag": "https://flagcdn.com/w320/co.png",
        "code": "CO",
        "continent": "Dél-Amerika",
        "callingCode": "+57",
        "area": "1,141,748 km²",
        "population": "50.9 millió",
        "language": "Spanyol",
        "capital": "Bogotá",
        "currency": "Peso (COP)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-79.0%2C-4.2%2C-66.9%2C12.5&layer=mapnik",
        "osmRelationId": "287760",
        "attractions": ["Cartagena", "Medellín", "Tayrona Nemzeti Park", "Ciudad Perdida", "Cocora völgy", "Guatapé", "San Andrés-sziget", "Tatacoa-sivatag", "Monserrate (Bogotá)", "Zipaquirái sókatedrális"]
    },
    "VE": {
        "name": "Venezuela",
        "flag": "🇻🇪",
        "officialFlag": "https://flagcdn.com/w320/ve.png",
        "code": "VE",
        "continent": "Dél-Amerika",
        "callingCode": "+58",
        "area": "916,445 km²",
        "population": "28.4 millió",
        "language": "Spanyol",
        "capital": "Caracas",
        "currency": "Bolívar (VES)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-73.4%2C0.6%2C-59.8%2C12.2&layer=mapnik",
        "osmRelationId": "272644",
        "attractions": ["Angel-vízesés", "Los Roques", "Canaima Nemzeti Park", "Mérida", "Margarita sziget", "Roraima-hegy", "Morrocoy Nemzeti Park", "Medanos de Coro Nemzeti Park", "Orinoco-delta", "Cueva del Guácharo"]
    },
    "GY": {
        "name": "Guyana",
        "flag": "🇬🇾",
        "officialFlag": "https://flagcdn.com/w320/gy.png",
        "code": "GY",
        "continent": "Dél-Amerika",
        "callingCode": "+592",
        "area": "214,969 km²",
        "population": "787,000",
        "language": "Angol",
        "capital": "Georgetown",
        "currency": "Guyanai dollár (GYD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-61.4%2C1.2%2C-56.5%2C8.6&layer=mapnik",
        "osmRelationId": "287082",
        "attractions": ["Kaieteur-vízesés", "Georgetown", "Iwokrama", "Rupununi", "Shell Beach", "Orinduik-vízesés", "Kanuku-hegység", "St. George's katedrális", "Demerara Harbour Bridge", "Surama falu"]
    },
    "SR": {
        "name": "Suriname",
        "flag": "🇸🇷",
        "officialFlag": "https://flagcdn.com/w320/sr.png",
        "code": "SR",
        "continent": "Dél-Amerika",
        "callingCode": "+597",
        "area": "163,820 km²",
        "population": "587,000",
        "language": "Holland",
        "capital": "Paramaribo",
        "currency": "Suriname dollár (SRD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-58.1%2C1.8%2C-53.9%2C6.0&layer=mapnik",
        "osmRelationId": "287083",
        "attractions": ["Paramaribo", "Brownsberg", "Galibi", "Raleighvallen", "Jodensavanne", "Central Suriname Természetvédelmi Terület", "Fort Zeelandia", "Szent Péter és Pál katedrális", "Commewijne folyó", "Peperpot Nemzeti Park"]
    },
    "GF": {
        "name": "Francia Guyana",
        "flag": "🇬🇫",
        "officialFlag": "https://flagcdn.com/w320/gf.png",
        "code": "GF",
        "continent": "Dél-Amerika",
        "callingCode": "+594",
        "area": "83,534 km²",
        "population": "290,000",
        "language": "Francia",
        "capital": "Cayenne",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-54.6%2C2.1%2C-51.6%2C5.8&layer=mapnik",
        "osmRelationId": "290068",
        "attractions": ["Kourou űrközpont", "Îles du Salut", "Cayenne", "Saint-Laurent-du-Maroni", "Amazónia", "Guiana Zoo", "Marais de Kaw-Roura", "Camp de la Transportation", "Plages de Rémire-Montjoly", "Fort Cépérou"]
    },
    "EC": {
        "name": "Ecuador",
        "flag": "🇪🇨",
        "officialFlag": "https://flagcdn.com/w320/ec.png",
        "code": "EC",
        "continent": "Dél-Amerika",
        "callingCode": "+593",
        "area": "283,561 km²",
        "population": "17.6 millió",
        "language": "Spanyol",
        "capital": "Quito",
        "currency": "Dollár (USD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-81.1%2C-5.0%2C-75.2%2C1.7&layer=mapnik",
        "osmRelationId": "108089",
        "attractions": ["Galápagos-szigetek", "Quito", "Cotopaxi", "Cuenca", "Baños", "Mitad del Mundo", "Otavalo piac", "Amazonas esőerdő", "Cajas Nemzeti Park", "Mindo köderdő"]
    },
    "PE": {
        "name": "Peru",
        "flag": "🇵🇪",
        "officialFlag": "https://flagcdn.com/w320/pe.png",
        "code": "PE",
        "continent": "Dél-Amerika",
        "callingCode": "+51",
        "area": "1,285,216 km²",
        "population": "33.0 millió",
        "language": "Spanyol, Quechua",
        "capital": "Lima",
        "currency": "Sol (PEN)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-81.3%2C-18.3%2C-68.7%2C-0.0&layer=mapnik",
        "osmRelationId": "288247",
        "attractions": ["Machu Picchu", "Cusco", "Nazca vonalak", "Titicaca-tó", "Arequipa", "Szent Völgy", "Colca-kanyon", "Huacachina oázis", "Manu Nemzeti Park", "Rainbow Mountain"]
    },
    "BO": {
        "name": "Bolívia",
        "flag": "🇧🇴",
        "officialFlag": "https://flagcdn.com/w320/bo.png",
        "code": "BO",
        "continent": "Dél-Amerika",
        "callingCode": "+591",
        "area": "1,098,581 km²",
        "population": "11.7 millió",
        "language": "Spanyol, Quechua, Aymara",
        "capital": "Sucre",
        "currency": "Boliviano (BOB)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-69.6%2C-22.9%2C-57.5%2C-9.7&layer=mapnik",
        "osmRelationId": "252645",
        "attractions": ["Salar de Uyuni", "La Paz", "Titicaca-tó", "Sucre", "Potosí", "Halálút (Yungas Road)", "Madidi Nemzeti Park", "Tiwanaku", "Laguna Colorada", "Isla del Sol"]
    },
    "CL": {
        "name": "Chile",
        "flag": "🇨🇱",
        "officialFlag": "https://flagcdn.com/w320/cl.png",
        "code": "CL",
        "continent": "Dél-Amerika",
        "callingCode": "+56",
        "area": "756,096 km²",
        "population": "19.1 millió",
        "language": "Spanyol",
        "capital": "Santiago",
        "currency": "Peso (CLP)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-75.6%2C-55.6%2C-66.4%2C-17.5&layer=mapnik",
        "osmRelationId": "167454",
        "attractions": ["Atacama sivatag", "Patagónia", "Húsvét-sziget", "Torres del Paine", "Valparaíso", "Márványbarlangok (Marble Caves)", "El Tatio gejzírek", "Chiloé-sziget", "Valle de la Luna", "Santiago"]
    },
    "PY": {
        "name": "Paraguay",
        "flag": "🇵🇾",
        "officialFlag": "https://flagcdn.com/w320/py.png",
        "code": "PY",
        "continent": "Dél-Amerika",
        "callingCode": "+595",
        "area": "406,752 km²",
        "population": "7.1 millió",
        "language": "Spanyol, Guaraní",
        "capital": "Asunción",
        "currency": "Guaraní (PYG)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-62.6%2C-27.6%2C-54.3%2C-19.3&layer=mapnik",
        "osmRelationId": "287077",
        "attractions": ["Asunción", "Iguazu-vízesés", "Jesuit Missions", "Pantanal", "Encarnación", "Itaipu-gát", "Ybycuí Nemzeti Park", "Cerro Corá Nemzeti Park", "Areguá", "San Bernardino"]
    },
    "UY": {
        "name": "Uruguay",
        "flag": "🇺🇾",
        "officialFlag": "https://flagcdn.com/w320/uy.png",
        "code": "UY",
        "continent": "Dél-Amerika",
        "callingCode": "+598",
        "area": "176,215 km²",
        "population": "3.5 millió",
        "language": "Spanyol",
        "capital": "Montevideo",
        "currency": "Peso (UYU)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-58.4%2C-35.0%2C-53.1%2C-30.1&layer=mapnik",
        "osmRelationId": "287072",
        "attractions": ["Montevideo", "Punta del Este", "Colonia del Sacramento", "Cabo Polonio", "Piriápolis", "Casapueblo", "Santa Teresa Nemzeti Park", "La Pedrera", "Termas del Daymán", "Plaza Independencia"]
    },
};