const Azsia = {
    "CN": {
        "name": "Kína",
        "flag": "🇨🇳",
        "officialFlag": "https://flagcdn.com/w320/cn.png",
        "code": "CN",
        "continent": "Ázsia",
        "callingCode": "+86",
        "area": "9,596,961 km²",
        "population": "1.4 milliárd",
        "language": "Mandarin kínai",
        "capital": "Peking",
        "currency": "Yuan (CNY)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=73.6%2C18.2%2C134.8%2C53.6&layer=mapnik",
        "osmRelationId": "270056",
        "attractions": ["Nagy Kínai Fal", "Tiltott Város", "Terrakotta hadsereg", "Li folyó", "Sanghaj", "Potala palota (Tibet)", "Zhangjiajie Nemzeti Park", "Pekingi Nyári Palota", "Pandarezervátum (Csengtu)", "Huang-hegy"],
        "alt_spellings": ["China", "CN", "Kína", "Zhongguo"]
    },
    "JP": {
        "name": "Japán",
        "flag": "🇯🇵",
        "officialFlag": "https://flagcdn.com/w320/jp.png",
        "code": "JP",
        "continent": "Ázsia",
        "callingCode": "+81",
        "area": "377,975 km²",
        "population": "125.8 millió",
        "language": "Japán",
        "capital": "Tokió",
        "currency": "Yen (JPY)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=129.4%2C31.0%2C145.8%2C45.6&layer=mapnik",
        "osmRelationId": "382313",
        "attractions": ["Fuji-hegy", "Tokió", "Kiotó", "Hiroshima", "Nara", "Aranytemplom (Kinkaku-ji)", "Oszaka", "Shibuya kereszteződés", "Ghibli Múzeum", "Hokkaido"],
        "alt_spellings": ["Japan", "JP", "Japán", "Nippon", "Nihon"]
    },
    "IN": {
        "name": "India",
        "flag": "🇮🇳",
        "officialFlag": "https://flagcdn.com/w320/in.png",
        "code": "IN",
        "continent": "Ázsia",
        "callingCode": "+91",
        "area": "3,287,263 km²",
        "population": "1.38 milliárd",
        "language": "Hindi, Angol",
        "capital": "Új-Delhi",
        "currency": "Rúpia (INR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=68.2%2C6.8%2C97.4%2C37.1&layer=mapnik",
        "osmRelationId": "304716",
        "attractions": ["Taj Mahal", "Gangesz", "Himalája", "Goa", "Rajasthan", "Varanasi", "Aranytemplom (Amritszár)", "Kerala holtágai", "Mumbai", "Hampi"],
        "alt_spellings": ["India", "IN", "Bharat", "Hindustan"]
    },
    "TH": {
        "name": "Thaiföld",
        "flag": "🇹🇭",
        "officialFlag": "https://flagcdn.com/w320/th.png",
        "code": "TH",
        "continent": "Ázsia",
        "callingCode": "+66",
        "area": "513,120 km²",
        "population": "69.8 millió",
        "language": "Thai",
        "capital": "Bangkok",
        "currency": "Baht (THB)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=97.3%2C5.6%2C105.6%2C20.5&layer=mapnik",
        "osmRelationId": "2067731",
        "attractions": ["Bangkok", "Phuket", "Chiang Mai", "Ayutthaya", "Koh Phi Phi", "Nagy Palota (Bangkok)", "Khao Sok Nemzeti Park", "Krabi", "Pattaya", "Similan-szigetek"],
        "alt_spellings": ["Thailand", "TH", "Thaiföld", "Prathet Thai"]
    },
    "VN": {
        "name": "Vietnám",
        "flag": "🇻🇳",
        "officialFlag": "https://flagcdn.com/w320/vn.png",
        "code": "VN",
        "continent": "Ázsia",
        "callingCode": "+84",
        "area": "331,212 km²",
        "population": "97.3 millió",
        "language": "Vietnámi",
        "capital": "Hanoi",
        "currency": "Dong (VND)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=102.1%2C8.6%2C109.5%2C23.4&layer=mapnik",
        "osmRelationId": "49915",
        "attractions": ["Ha Long-öböl", "Ho Si Minh-város", "Hoi An", "Sapa", "Mekong Delta", "Cu Chi alagutak", "Hue", "Phong Nha-Ke Bang Nemzeti Park", "Nha Trang", "Phu Quoc sziget"],
        "alt_spellings": ["Vietnam", "VN", "Vietnám", "Cộng hòa Xã hội chủ nghĩa Việt Nam"]
    },
    "ID": {
        "name": "Indonézia",
        "flag": "🇮🇩",
        "officialFlag": "https://flagcdn.com/w320/id.png",
        "code": "ID",
        "continent": "Ázsia",
        "callingCode": "+62",
        "area": "1,904,569 km²",
        "population": "273.5 millió",
        "language": "Indonéz",
        "capital": "Jakarta",
        "currency": "Rúpia (IDR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=95.0%2C-11.0%2C141.0%2C6.0&layer=mapnik",
        "osmRelationId": "304753",
        "attractions": ["Bali", "Borobudur", "Komodo szigetek", "Jakarta", "Yogyakarta", "Bromo-Tengger-Semeru Nemzeti Park", "Raja Ampat-szigetek", "Tana Toraja", "Gili-szigetek", "Ubud"],
        "alt_spellings": ["Indonesia", "ID", "Indonézia", "Republik Indonesia"]
    },
    "MY": {
        "name": "Malajzia",
        "flag": "🇲🇾",
        "officialFlag": "https://flagcdn.com/w320/my.png",
        "code": "MY",
        "continent": "Ázsia",
        "callingCode": "+60",
        "area": "329,847 km²",
        "population": "32.4 millió",
        "language": "Malay",
        "capital": "Kuala Lumpur",
        "currency": "Ringgit (MYR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=99.6%2C0.9%2C119.3%2C7.4&layer=mapnik",
        "osmRelationId": "2108121",
        "attractions": ["Petronas Towers", "Penang", "Langkawi", "Cameron Highlands", "Borneo", "Batu-barlangok", "Taman Negara Nemzeti Park", "Malacca", "Kinabalu-hegy", "Perhentian-szigetek"],
        "alt_spellings": ["Malaysia", "MY", "Malajzia"]
    },
    "SG": {
        "name": "Szingapúr",
        "flag": "🇸🇬",
        "officialFlag": "https://flagcdn.com/w320/sg.png",
        "code": "SG",
        "continent": "Ázsia",
        "callingCode": "+65",
        "area": "719 km²",
        "population": "5.9 millió",
        "language": "Angol, Mandarin, Malay, Tamil",
        "capital": "Szingapúr",
        "currency": "Dollár (SGD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=103.6%2C1.2%2C104.0%2C1.5&layer=mapnik",
        "osmRelationId": "536780",
        "attractions": ["Marina Bay Sands", "Gardens by the Bay", "Sentosa", "Chinatown", "Little India", "Szingapúri Állatkert", "Orchard Road", "Jewel Changi Airport", "Clarke Quay", "Merlion Park"],
        "alt_spellings": ["Singapore", "SG", "Szingapúr", "Republic of Singapore"]
    },
    "PH": {
        "name": "Fülöp-szigetek",
        "flag": "🇵🇭",
        "officialFlag": "https://flagcdn.com/w320/ph.png",
        "code": "PH",
        "continent": "Ázsia",
        "callingCode": "+63",
        "area": "300,000 km²",
        "population": "109.0 millió",
        "language": "Filipino, Angol",
        "capital": "Manila",
        "currency": "Peso (PHP)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=116.9%2C4.6%2C126.6%2C21.1&layer=mapnik",
        "osmRelationId": "48459",
        "attractions": ["Boracay", "Palawan", "Bohol", "Manila", "Cebu", "El Nido", "Coron", "Csokoládé-hegyek", "Banaue rizsteraszok", "Siargao"]
    },
    "KR": {
        "name": "Dél-Korea",
        "flag": "🇰🇷",
        "officialFlag": "https://flagcdn.com/w320/kr.png",
        "code": "KR",
        "continent": "Ázsia",
        "callingCode": "+82",
        "area": "100,210 km²",
        "population": "51.8 millió",
        "language": "Koreai",
        "capital": "Szöul",
        "currency": "Won (KRW)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=125.0%2C33.1%2C129.6%2C38.6&layer=mapnik",
        "osmRelationId": "304913",
        "attractions": ["Szöul", "Jeju sziget", "Busan", "Gyeongju", "Seoraksan", "DMZ (Demilitarizált övezet)", "Gyeongbokgung palota", "N Seoul Tower", "Hahoe népi falu", "Bukhansan Nemzeti Park"]
    },
    "TR": {
        "name": "Törökország",
        "flag": "🇹🇷",
        "officialFlag": "https://flagcdn.com/w320/tr.png",
        "code": "TR",
        "continent": "Ázsia",
        "callingCode": "+90",
        "area": "783,562 km²",
        "population": "84.3 millió",
        "language": "Török",
        "capital": "Ankara",
        "currency": "Líra (TRY)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=26.0%2C35.8%2C44.8%2C42.1&layer=mapnik",
        "osmRelationId": "174737",
        "attractions": ["Isztambul", "Kappadókia", "Pamukkale", "Efézus", "Antalya", "Hagia Sophia", "Kék mecset", "Topkapi palota", "Líciai part", "Nemrut-hegy"]
    },
    "IL": {
        "name": "Izrael",
        "flag": "🇮🇱",
        "officialFlag": "https://flagcdn.com/w320/il.png",
        "code": "IL",
        "continent": "Ázsia",
        "callingCode": "+972",
        "area": "20,770 km²",
        "population": "9.4 millió",
        "language": "Héber, Arab",
        "capital": "Jeruzsálem",
        "currency": "Sékel (ILS)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=34.3%2C29.5%2C35.9%2C33.3&layer=mapnik",
        "osmRelationId": "1473946",
        "attractions": ["Jeruzsálem", "Tel Aviv", "Holt-tenger", "Masada", "Nazaret", "Siratófal", "Szikladóm", "Yad Vashem", "Galileai-tenger", "Eilat"]
    },
    "IR": {
        "name": "Irán",
        "flag": "🇮🇷",
        "officialFlag": "https://flagcdn.com/w320/ir.png",
        "code": "IR",
        "continent": "Ázsia",
        "callingCode": "+98",
        "area": "1,648,195 km²",
        "population": "84.0 millió",
        "language": "Perzsa",
        "capital": "Teherán",
        "currency": "Rial (IRR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=44.0%2C25.1%2C63.3%2C39.8&layer=mapnik",
        "osmRelationId": "304938",
        "attractions": ["Persepolis", "Isfahan", "Shiraz", "Teherán", "Yazd", "Naqsh-e Jahan tér", "Golestan palota", "Fin kert", "Abyaneh falu", "Kish-sziget"]
    },
    "SA": {
        "name": "Szaúd-Arábia",
        "flag": "🇸🇦",
        "officialFlag": "https://flagcdn.com/w320/sa.png",
        "code": "SA",
        "continent": "Ázsia",
        "callingCode": "+966",
        "area": "2,149,690 km²",
        "population": "34.8 millió",
        "language": "Arab",
        "capital": "Rijád",
        "currency": "Riyal (SAR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=34.5%2C16.4%2C55.7%2C32.2&layer=mapnik",
        "osmRelationId": "304948",
        "attractions": ["Mekka", "Medina", "Rijád", "Jeddah", "Al-Ula", "Mada'in Saleh", "Kingdom Centre Tower", "Edge of the World", "Farasan-szigetek", "Al-Masjid an-Nabawi"]
    },
    "PK": {
        "name": "Pakisztán",
        "flag": "🇵🇰",
        "officialFlag": "https://flagcdn.com/w320/pk.png",
        "code": "PK",
        "continent": "Ázsia",
        "callingCode": "+92",
        "area": "881,913 km²",
        "population": "225.2 millió",
        "language": "Urdu, Angol",
        "capital": "Iszlámábád",
        "currency": "Rúpia (PKR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=60.9%2C23.7%2C77.8%2C37.1&layer=mapnik",
        "osmRelationId": "304940",
        "attractions": ["K2", "Lahore", "Karachi", "Hunza völgy", "Skardu", "Badshahi mecset", "Faisal mecset", "Mohendzsodáro", "Karakoram Highway", "Deosai Nemzeti Park"]
    },
    "BD": {
        "name": "Banglades",
        "flag": "🇧🇩",
        "officialFlag": "https://flagcdn.com/w320/bd.png",
        "code": "BD",
        "continent": "Ázsia",
        "callingCode": "+880",
        "area": "147,570 km²",
        "population": "165.0 millió",
        "language": "Bengáli",
        "capital": "Dhaka",
        "currency": "Taka (BDT)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=88.0%2C20.7%2C92.7%2C26.6&layer=mapnik",
        "osmRelationId": "184640",
        "attractions": ["Sundarbans", "Cox's Bazar", "Dhaka", "Sylhet", "Chittagong", "Paharpur", "Srimangal", "Saint Martin-sziget", "Lalbagh Fort", "Ahsan Manzil"]
    },
    "MN": {
        "name": "Mongólia",
        "flag": "🇲🇳",
        "officialFlag": "https://flagcdn.com/w320/mn.png",
        "code": "MN",
        "continent": "Ázsia",
        "callingCode": "+976",
        "area": "1,564,110 km²",
        "population": "3.3 millió",
        "language": "Mongol",
        "capital": "Ulánbátor",
        "currency": "Tugrik (MNT)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=87.7%2C41.6%2C119.9%2C52.1&layer=mapnik",
        "osmRelationId": "161252",
        "attractions": ["Gobi sivatag", "Ulánbátor", "Khövsgöl-tó", "Karakorum", "Altai hegység", "Terelj Nemzeti Park", "Dzsingisz kán lovas szobra", "Flaming Cliffs", "Erdene Zuu kolostor", "Hustain Nuruu Nemzeti Park"]
    },
    "NP": {
        "name": "Nepál",
        "flag": "🇳🇵",
        "officialFlag": "https://flagcdn.com/w320/np.png",
        "code": "NP",
        "continent": "Ázsia",
        "callingCode": "+977",
        "area": "147,181 km²",
        "population": "29.1 millió",
        "language": "Nepáli",
        "capital": "Katmandu",
        "currency": "Rúpia (NPR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=80.1%2C26.4%2C88.2%2C30.4&layer=mapnik",
        "osmRelationId": "184633",
        "attractions": ["Mount Everest", "Katmandu", "Pokhara", "Chitwan", "Lumbini", "Annapurna Circuit", "Boudhanath sztúpa", "Pashupatinath templom", "Swayambhunath sztúpa", "Bhaktapur"]
    },
    "LK": {
        "name": "Srí Lanka",
        "flag": "🇱🇰",
        "officialFlag": "https://flagcdn.com/w320/lk.png",
        "code": "LK",
        "continent": "Ázsia",
        "callingCode": "+94",
        "area": "65,610 km²",
        "population": "21.9 millió",
        "language": "Szingaléz, Tamil",
        "capital": "Colombo",
        "currency": "Rúpia (LKR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=79.7%2C5.9%2C81.9%2C9.8&layer=mapnik",
        "osmRelationId": "536823",
        "attractions": ["Sigiriya", "Kandy", "Galle", "Nuwara Eliya", "Yala Nemzeti Park", "Fog temploma", "Dambulla sziklatemplom", "Adam's Peak", "Ella", "Mirissa"]
    },
};