 const Europa = {"HU": {
        "name": "Magyarország",
        "flag": "🇭🇺",
        "officialFlag": "https://flagcdn.com/hu.svg",
        "code": "HU",
        "continent": "Európa",
        "callingCode": "+36",
        "area": "93,028 km²",
        "population": "9.7 millió",
        "language": "Magyar",
        "capital": "Budapest",
        "currency": "Forint (HUF)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=16.1138916015625%2C45.737995808419616%2C22.906494140625%2C48.585194057760035&layer=mapnik",
        "osmRelationId": "49915",
        "attractions": ["Parlament", "Széchenyi fürdő", "Halászbástya", "Balaton", "Hortobágy", "Egri vár", "Tokaji borvidék", "Pécsi ókeresztény sírkamrák", "Hollókő", "Aggteleki-karszt"],
        "alt_spellings": ["Hungary", "Magyarország", "HU"]
    },
    "DE": {
        "name": "Németország",
        "flag": "🇩🇪",
        "officialFlag": "https://flagcdn.com/w320/de.png",
        "code": "DE",
        "continent": "Európa",
        "callingCode": "+49",
        "area": "357,022 km²",
        "population": "83.2 millió",
        "language": "Német",
        "capital": "Berlin",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=5.866699218750001%2C47.270114637343%2C15.0421142578125%2C55.065787461051005&layer=mapnik",
        "osmRelationId": "51477",
        "attractions": ["Brandenburg-kapu", "Neuschwanstein kastély", "Oktoberfest", "Rajna-völgy", "Fekete-erdő", "Kölni dóm", "Hamburg Speicherstadt", "Berlini fal (East Side Gallery)", "Drezdai Frauenkirche", "Zugspitze"],
        "alt_spellings": ["Germany", "Deutschland", "DE", "Németország"]
    },
    "FR": {
        "name": "Franciaország",
        "flag": "🇫🇷",
        "officialFlag": "https://flagcdn.com/w320/fr.png",
        "code": "FR",
        "continent": "Európa",
        "callingCode": "+33",
        "area": "643,801 km²",
        "population": "67.4 millió",
        "language": "Francia",
        "capital": "Párizs",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-4.7900390625%2C42.032974332441405%2C8.0859375%2C51.17934297928927&layer=mapnik",
        "osmRelationId": "1102455",
        "attractions": ["Eiffel-torony", "Louvre", "Versailles", "Mont Blanc", "Provence", "Mont Saint-Michel", "Francia Riviéra (Côte d'Azur)", "Loire-völgyi kastélyok", "Notre-Dame-székesegyház", "D-napi partraszállás helyszínei"],
        "alt_spellings": ["France", "FR", "Franciaország"]
    },
    "CH": {
        "name": "Svájc",
        "flag": "🇨🇭",
        "officialFlag": "https://flagcdn.com/w320/ch.png",
        "code": "CH",
        "continent": "Európa",
        "callingCode": "+41",
        "area": "41,285 km²",
        "population": "8.7 millió",
        "language": "Német, Francia, Olasz, Rétoromán",
        "capital": "Bern",
        "currency": "Svájci frank (CHF)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=5.9%2C45.8%2C10.5%2C47.8&layer=mapnik",
        "osmRelationId": "51701",
        "attractions": ["Matterhorn", "Jungfraujoch", "Genfi-tó", "Zermatt", "Interlaken", "Luzern és a Kápolna-híd", "Chillon vára", "St. Moritz", "Bern óvárosa", "Rajna-vízesés"],
        "alt_spellings": ["Switzerland", "Schweiz", "Suisse", "Svizzera", "CH", "Svájc"]
    },
    "AT": {
        "name": "Ausztria",
        "flag": "🇦🇹",
        "officialFlag": "https://flagcdn.com/w320/at.png",
        "code": "AT",
        "continent": "Európa",
        "callingCode": "+43",
        "area": "83,879 km²",
        "population": "9.0 millió",
        "language": "Német",
        "capital": "Bécs",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=9.5%2C46.4%2C17.2%2C49.0&layer=mapnik",
        "osmRelationId": "16239",
        "attractions": ["Schönbrunn", "Salzburg", "Hallstatt", "Alpok", "Melk apátság", "Hofburg (Bécs)", "Grossglockner", "Innsbruck óvárosa", "Eisriesenwelt jégbarlang", "Belvedere kastély"],
        "alt_spellings": ["Austria", "Österreich", "AT", "Ausztria"]
    },
    "IT": {
        "name": "Olaszország",
        "flag": "🇮🇹",
        "officialFlag": "https://flagcdn.com/w320/it.png",
        "code": "IT",
        "continent": "Európa",
        "callingCode": "+39",
        "area": "301,340 km²",
        "population": "60.4 millió",
        "language": "Olasz",
        "capital": "Róma",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=6.6%2C35.5%2C18.5%2C47.1&layer=mapnik",
        "osmRelationId": "365331",
        "attractions": ["Colosseum", "Vatikán", "Velence", "Toszkána", "Amalfi-part", "Firenzei dóm", "Pompeii romjai", "Cinque Terre", "Uffizi Képtár", "Dolomitok"],
        "alt_spellings": ["Italy", "Italia", "IT", "Olaszország"]
    },
    "ES": {
        "name": "Spanyolország",
        "flag": "🇪🇸",
        "officialFlag": "https://flagcdn.com/w320/es.png",
        "code": "ES",
        "continent": "Európa",
        "callingCode": "+34",
        "area": "505,992 km²",
        "population": "47.4 millió",
        "language": "Spanyol",
        "capital": "Madrid",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-9.3%2C35.2%2C3.3%2C43.8&layer=mapnik",
        "osmRelationId": "1311341",
        "attractions": ["Sagrada Familia", "Alhambra", "Prado múzeum", "Sevilla", "Camino de Santiago", "Ibiza", "Park Güell", "Mezquita (Córdoba)", "Guggenheim Múzeum (Bilbao)", "Teide Nemzeti Park"],
        "alt_spellings": ["Spain", "España", "ES", "Spanyolország"]
    },
    "PT": {
        "name": "Portugália",
        "flag": "🇵🇹",
        "officialFlag": "https://flagcdn.com/w320/pt.png",
        "code": "PT",
        "continent": "Európa",
        "callingCode": "+351",
        "area": "92,212 km²",
        "population": "10.3 millió",
        "language": "Portugál",
        "capital": "Lisszabon",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-9.5%2C36.9%2C-6.2%2C42.2&layer=mapnik",
        "osmRelationId": "295480",
        "attractions": ["Belém torony", "Porto", "Sintra", "Algarve", "Óbidos", "Jeromosok kolostora", "Pena Palota", "Douro-völgy", "Madeira", "Azori-szigetek"],
        "alt_spellings": ["Portugal", "PT", "Portugália"]
    },
    "GB": {
        "name": "Egyesült Királyság",
        "flag": "🇬🇧",
        "officialFlag": "https://flagcdn.com/w320/gb.png",
        "code": "GB",
        "continent": "Európa",
        "callingCode": "+44",
        "area": "243,610 km²",
        "population": "67.3 millió",
        "language": "Angol",
        "capital": "London",
        "currency": "Font sterling (GBP)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-8.6%2C49.9%2C1.8%2C60.8&layer=mapnik",
        "osmRelationId": "62149",
        "attractions": ["Big Ben", "Stonehenge", "Edinburgh Castle", "Lake District", "Tower Bridge", "Buckingham-palota", "Skót-felföld", "London Eye", "British Museum", "Cornwall partvidéke"],
        "alt_spellings": ["United Kingdom", "UK", "Great Britain", "GB", "Egyesült Királyság"]
    },
    "IE": {
        "name": "Írország",
        "flag": "🇮🇪",
        "officialFlag": "https://flagcdn.com/w320/ie.png",
        "code": "IE",
        "continent": "Európa",
        "callingCode": "+353",
        "area": "70,273 km²",
        "population": "5.0 millió",
        "language": "Angol, Ír",
        "capital": "Dublin",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-10.5%2C51.4%2C-6.0%2C55.4&layer=mapnik",
        "osmRelationId": "330292",
        "attractions": ["Cliffs of Moher", "Ring of Kerry", "Giant's Causeway", "Dublin", "Killarney", "Guinness Storehouse", "Blarney kastély", "Galway", "Skellig Michael", "Newgrange"],
        "alt_spellings": ["Ireland", "Éire", "IE", "Írország"]
    },
    "NL": {
        "name": "Hollandia",
        "flag": "🇳🇱",
        "officialFlag": "https://flagcdn.com/w320/nl.png",
        "code": "NL",
        "continent": "Európa",
        "callingCode": "+31",
        "area": "41,543 km²",
        "population": "17.4 millió",
        "language": "Holland",
        "capital": "Amsterdam",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=3.4%2C50.8%2C7.2%2C53.6&layer=mapnik",
        "osmRelationId": "27599",
        "attractions": ["Keukenhof", "Anne Frank ház", "Kinderdijk", "Zaanse Schans", "Rijksmuseum", "Van Gogh Múzeum", "Amszterdami csatornák", "Hoge Veluwe Nemzeti Park", "Maastricht", "Giethoorn"],
        "alt_spellings": ["Netherlands", "Holland", "Hollandia"]
    },
    "BE": {
        "name": "Belgium",
        "flag": "🇧🇪",
        "officialFlag": "https://flagcdn.com/w320/be.png",
        "code": "BE",
        "continent": "Európa",
        "callingCode": "+32",
        "area": "30,528 km²",
        "population": "11.5 millió",
        "language": "Holland, Francia, Német",
        "capital": "Brüsszel",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=2.5%2C49.5%2C6.4%2C51.5&layer=mapnik",
        "osmRelationId": "52411",
        "attractions": ["Grand Place", "Atomium", "Bruges", "Ghent", "Waterloo", "Ardennek", "Antwerpen", "Dinant", "Manneken Pis", "Leuveni városháza"],
        "alt_spellings": ["Belgium", "België", "Belgique", "BE", "Belgium"]
    },
    "LU": {
        "name": "Luxemburg",
        "flag": "🇱🇺",
        "officialFlag": "https://flagcdn.com/w320/lu.png",
        "code": "LU",
        "continent": "Európa",
        "callingCode": "+352",
        "area": "2,586 km²",
        "population": "634,000",
        "language": "Luxemburgi, Francia, Német",
        "capital": "Luxemburg",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=5.7%2C49.4%2C6.5%2C50.2&layer=mapnik",
        "osmRelationId": "2171347",
        "attractions": ["Luxemburg óváros", "Vianden kastély", "Müllerthal", "Echternach", "Clervaux", "Bock kazamaták", "Adolphe híd", "Moselle-völgy", "Esch-sur-Sûre", "Nemzeti Múzeum"],
        "alt_spellings": ["Luxembourg", "Lëtzebuerg", "LU", "Luxemburg"]
    },
    "DK": {
        "name": "Dánia",
        "flag": "🇩🇰",
        "officialFlag": "https://flagcdn.com/w320/dk.png",
        "code": "DK",
        "continent": "Európa",
        "callingCode": "+45",
        "area": "43,094 km²",
        "population": "5.8 millió",
        "language": "Dán",
        "capital": "Koppenhága",
        "currency": "Dán korona (DKK)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=8.1%2C54.6%2C15.2%2C57.7&layer=mapnik",
        "osmRelationId": "50046",
        "attractions": ["Tivoli", "Kis hableány", "Nyhavn", "Kronborg kastély", "Legoland", "Roskildei dóm", "Aarhus", "Skagen", "Christiansborg Palota", "Bornholm szigete"]
    },
    "SE": {
        "name": "Svédország",
        "flag": "🇸🇪",
        "officialFlag": "https://flagcdn.com/w320/se.png",
        "code": "SE",
        "continent": "Európa",
        "callingCode": "+46",
        "area": "450,295 km²",
        "population": "10.4 millió",
        "language": "Svéd",
        "capital": "Stockholm",
        "currency": "Svéd korona (SEK)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=11.1%2C55.3%2C24.2%2C69.1&layer=mapnik",
        "osmRelationId": "52822",
        "attractions": ["Stockholm óváros", "Vasa múzeum", "Göteborg", "Malmö", "Lapland", "Skansen", "Drottningholm palota", "ICEHOTEL", "Abisko Nemzeti Park", "Gotland szigete"]
    },
    "NO": {
        "name": "Norvégia",
        "flag": "🇳🇴",
        "officialFlag": "https://flagcdn.com/w320/no.png",
        "code": "NO",
        "continent": "Európa",
        "callingCode": "+47",
        "area": "385,207 km²",
        "population": "5.4 millió",
        "language": "Norvég",
        "capital": "Oslo",
        "currency": "Norvég korona (NOK)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=4.6%2C58.0%2C31.3%2C71.2&layer=mapnik",
        "osmRelationId": "2978650",
        "attractions": ["Geirangerfjord", "Északi fény", "Bergen", "Lofoten szigetek", "Preikestolen", "Trolltunga", "Vigeland Park (Oslo)", "Flåm vasút", "Északi-fok", "Bryggen (Bergen)"]
    },
    "FI": {
        "name": "Finnország",
        "flag": "🇫🇮",
        "officialFlag": "https://flagcdn.com/w320/fi.png",
        "code": "FI",
        "continent": "Európa",
        "callingCode": "+358",
        "area": "338,424 km²",
        "population": "5.5 millió",
        "language": "Finn, Svéd",
        "capital": "Helsinki",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=20.5%2C59.8%2C31.6%2C70.1&layer=mapnik",
        "osmRelationId": "54224",
        "attractions": ["Helsinki", "Lapland", "Turku", "Tampere", "Saimaa-tó", "Suomenlinna erőd", "Mikulásfalu (Rovaniemi)", "Nuuksio Nemzeti Park", "Olavinlinna kastély", "Sziklatemplom (Temppeliaukio)"]
    },
    "IS": {
        "name": "Izland",
        "flag": "🇮🇸",
        "officialFlag": "https://flagcdn.com/w320/is.png",
        "code": "IS",
        "continent": "Európa",
        "callingCode": "+354",
        "area": "103,000 km²",
        "population": "372,000",
        "language": "Izlandi",
        "capital": "Reykjavik",
        "currency": "Izlandi korona (ISK)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-24.5%2C63.4%2C-13.5%2C66.6&layer=mapnik",
        "osmRelationId": "299133",
        "attractions": ["Geysir", "Gullfoss", "Kék Lagúna", "Északi fény", "Thingvellir", "Jökulsárlón gleccserlagúna", "Vatnajökull Nemzeti Park", "Fekete homokos part (Reynisfjara)", "Skógafoss vízesés", "Hallgrímskirkja"]
    },
    "PL": {
        "name": "Lengyelország",
        "flag": "🇵🇱",
        "officialFlag": "https://flagcdn.com/w320/pl.png",
        "code": "PL",
        "continent": "Európa",
        "callingCode": "+48",
        "area": "312,696 km²",
        "population": "38.0 millió",
        "language": "Lengyel",
        "capital": "Varsó",
        "currency": "Zloty (PLN)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=14.1%2C49.0%2C24.1%2C54.8&layer=mapnik",
        "osmRelationId": "49715",
        "attractions": ["Krakkó", "Auschwitz", "Gdansk", "Wrocław", "Zakopane", "Wieliczkai sóbánya", "Malborki kastély", "Varsó óvárosa", "Białowieża erdő", "Mazuri-tóvidék"]
    },
    "CZ": {
        "name": "Csehország",
        "flag": "🇨🇿",
        "officialFlag": "https://flagcdn.com/w320/cz.png",
        "code": "CZ",
        "continent": "Európa",
        "callingCode": "+420",
        "area": "78,867 km²",
        "population": "10.7 millió",
        "language": "Cseh",
        "capital": "Prága",
        "currency": "Cseh korona (CZK)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=12.1%2C48.6%2C18.9%2C51.1&layer=mapnik",
        "osmRelationId": "51684",
        "attractions": ["Prágai vár", "Károly híd", "Český Krumlov", "Brno", "Karlovy Vary", "Kutná Hora", "Cseh Svájc Nemzeti Park", "Telč", "Lednice-Valtice kultúrtáj", "Pilsen"]
    },
    "SK": {
        "name": "Szlovákia",
        "flag": "🇸🇰",
        "officialFlag": "https://flagcdn.com/w320/sk.png",
        "code": "SK",
        "continent": "Európa",
        "callingCode": "+421",
        "area": "49,035 km²",
        "population": "5.5 millió",
        "language": "Szlovák",
        "capital": "Pozsony",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=16.8%2C47.7%2C22.6%2C49.6&layer=mapnik",
        "osmRelationId": "14296",
        "attractions": ["Spiš kastély", "Bojnice kastély", "Magas-Tátra", "Orava kastély", "Bardejov", "Pozsonyi vár", "Szlovák Paradicsom Nemzeti Park", "Demänovská Szabadság-barlang", "Vlkolínec", "Kassa (Košice)"]
    },
    "SI": {
        "name": "Szlovénia",
        "flag": "🇸🇮",
        "officialFlag": "https://flagcdn.com/w320/si.png",
        "code": "SI",
        "continent": "Európa",
        "callingCode": "+386",
        "area": "20,273 km²",
        "population": "2.1 millió",
        "language": "Szlovén",
        "capital": "Ljubljana",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=13.4%2C45.4%2C16.6%2C46.9&layer=mapnik",
        "osmRelationId": "218657",
        "attractions": ["Bled-tó", "Ljubljana", "Postojna barlang", "Piran", "Triglav", "Škocjan-barlangrendszer", "Predjama kastély", "Soča-völgy", "Bohinji-tó", "Maribor"]
    },
    "HR": {
        "name": "Horvátország",
        "flag": "🇭🇷",
        "officialFlag": "https://flagcdn.com/w320/hr.png",
        "code": "HR",
        "continent": "Európa",
        "callingCode": "+385",
        "area": "56,594 km²",
        "population": "3.9 millió",
        "language": "Horvát",
        "capital": "Zágráb",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=13.5%2C42.4%2C19.4%2C46.5&layer=mapnik",
        "osmRelationId": "214885",
        "attractions": ["Dubrovnik", "Plitvicei tavak", "Split", "Hvar", "Rovinj", "Krka Nemzeti Park", "Zadar (Tengeri orgona)", "Pula Aréna", "Korčula", "Zlatni Rat (Bol)"]
    },
        "BA": {
        "name": "Bosznia-Hercegovina",
        "flag": "🇧🇦",
        "officialFlag": "https://flagcdn.com/w320/ba.png",
        "code": "BA",
        "continent": "Európa",
        "callingCode": "+387",
        "area": "51,197 km²",
        "population": "3.3 millió",
        "language": "Bosnyák, Horvát, Szerb",
        "capital": "Szarajevó",
        "currency": "Konvertibilis márka (BAM)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=15.7%2C42.6%2C19.6%2C45.3&layer=mapnik",
        "osmRelationId": "2528142",
        "attractions": ["Szarajevó", "Mostar", "Banja Luka", "Trebinje", "Jajce", "Kravica-vízesés", "Blagaj Tekke", "Una Nemzeti Park", "Višegrádi híd", "Počitelj"]
    },
    "ME": {
        "name": "Montenegró",
        "flag": "🇲🇪",
        "officialFlag": "https://flagcdn.com/w320/me.png",
        "code": "ME",
        "continent": "Európa",
        "callingCode": "+382",
        "area": "13,812 km²",
        "population": "628,000",
        "language": "Montenegrói",
        "capital": "Podgorica",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=18.4%2C41.9%2C20.4%2C43.6&layer=mapnik",
        "osmRelationId": "53296",
        "attractions": ["Kotor", "Budva", "Durmitor", "Skadar-tó", "Sveti Stefan", "Ostrog kolostor", "Perast", "Tara-kanyon", "Lovćen Nemzeti Park", "Ulcinj"]
    },
    "AL": {
        "name": "Albánia",
        "flag": "🇦🇱",
        "officialFlag": "https://flagcdn.com/w320/al.png",
        "code": "AL",
        "continent": "Európa",
        "callingCode": "+355",
        "area": "28,748 km²",
        "population": "2.8 millió",
        "language": "Albán",
        "capital": "Tirana",
        "currency": "Lek (ALL)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=19.3%2C39.6%2C21.1%2C42.7&layer=mapnik",
        "osmRelationId": "72277",
        "attractions": ["Tirana", "Berat", "Gjirokastër", "Saranda", "Shkodër", "Butrint", "Albán Riviéra", "Koman-tó", "Theth Nemzeti Park", "Apollonia"]
    },
    "MK": {
        "name": "Észak-Macedónia",
        "flag": "🇲🇰",
        "officialFlag": "https://flagcdn.com/w320/mk.png",
        "code": "MK",
        "continent": "Európa",
        "callingCode": "+389",
        "area": "25,713 km²",
        "population": "2.1 millió",
        "language": "Macedón",
        "capital": "Skopje",
        "currency": "Macedón denár (MKD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=20.5%2C40.9%2C23.0%2C42.4&layer=mapnik",
        "osmRelationId": "53293",
        "attractions": ["Ohrid", "Skopje", "Bitola", "Prilep", "Mavrovo", "Matka-kanyon", "Szent Naum kolostor", "Heraclea Lyncestis", "Galičica Nemzeti Park", "Kamen Kukli"]
    },
    "BG": {
        "name": "Bulgária",
        "flag": "🇧🇬",
        "officialFlag": "https://flagcdn.com/w320/bg.png",
        "code": "BG",
        "continent": "Európa",
        "callingCode": "+359",
        "area": "110,879 km²",
        "population": "6.9 millió",
        "language": "Bolgár",
        "capital": "Szófia",
        "currency": "Leva (BGN)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=22.4%2C41.2%2C28.6%2C44.2&layer=mapnik",
        "osmRelationId": "186382",
        "attractions": ["Rila kolostor", "Plovdiv", "Veliko Tarnovo", "Nessebar", "Bansko", "Hét rilai tó", "Alekszandr Nyevszkij-székesegyház (Szófia)", "Belogradcsiki sziklák", "Koprivshtitsa", "Fekete-tenger partja"]
    },
    "RO": {
        "name": "Románia",
        "flag": "🇷🇴",
        "officialFlag": "https://flagcdn.com/w320/ro.png",
        "code": "RO",
        "continent": "Európa",
        "callingCode": "+40",
        "area": "238,391 km²",
        "population": "19.1 millió",
        "language": "Román",
        "capital": "Bukarest",
        "currency": "Lej (RON)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=20.3%2C43.6%2C29.7%2C48.3&layer=mapnik",
        "osmRelationId": "90689",
        "attractions": ["Bran kastély", "Peleș kastély", "Bukarest", "Brașov", "Sighișoara", "Transzfogarasi út", "Duna-delta", "Vajdahunyad vára", "Festett kolostorok (Bukovinában)", "Tordai sóbánya"]
    },
    "MD": {
        "name": "Moldávia",
        "flag": "🇲🇩",
        "officialFlag": "https://flagcdn.com/w320/md.png",
        "code": "MD",
        "continent": "Európa",
        "callingCode": "+373",
        "area": "33,846 km²",
        "population": "2.6 millió",
        "language": "Román",
        "capital": "Chișinău",
        "currency": "Moldáv lej (MDL)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=26.6%2C45.5%2C30.1%2C48.5&layer=mapnik",
        "osmRelationId": "58974",
        "attractions": ["Chișinău", "Orheiul Vechi", "Cricova", "Saharna", "Soroca", "Mileștii Mici pincészet", "Transznisztria (Tiraspol)", "Căpriana kolostor", "Benderi erőd", "Tipova kolostor"]
    },
    "UA": {
        "name": "Ukrajna",
        "flag": "🇺🇦",
        "officialFlag": "https://flagcdn.com/w320/ua.png",
        "code": "UA",
        "continent": "Európa",
        "callingCode": "+380",
        "area": "603,550 km²",
        "population": "41.2 millió",
        "language": "Ukrán",
        "capital": "Kijev",
        "currency": "Hrivnya (UAH)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=22.1%2C44.4%2C40.2%2C52.4&layer=mapnik",
        "osmRelationId": "60189",
        "attractions": ["Kijev", "Lviv", "Odessa", "Kárpátok", "Kamianets-Podilskyi", "Pecserszka Lavra (Barlangkolostor)", "Csernobil", "Hoverla hegy", "Hotini erőd", "Szerelem alagútja (Klevan)"]
    },
    "BY": {
        "name": "Belarusz",
        "flag": "🇧🇾",
        "officialFlag": "https://flagcdn.com/w320/by.png",
        "code": "BY",
        "continent": "Európa",
        "callingCode": "+375",
        "area": "207,600 km²",
        "population": "9.4 millió",
        "language": "Belarusz, Orosz",
        "capital": "Minsk",
        "currency": "Belarusz rubel (BYN)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=23.2%2C51.3%2C32.8%2C56.2&layer=mapnik",
        "osmRelationId": "59065",
        "attractions": ["Minsk", "Brest", "Grodno", "Vitebsk", "Belovezhskaya Pushcha", "Miri vár", "Nyaszvizsi vár", "Braslav tavak", "Polack", "Gomel palota"]
    },
    "LT": {
        "name": "Litvánia",
        "flag": "🇱🇹",
        "officialFlag": "https://flagcdn.com/w320/lt.png",
        "code": "LT",
        "continent": "Európa",
        "callingCode": "+370",
        "area": "65,300 km²",
        "population": "2.8 millió",
        "language": "Litván",
        "capital": "Vilnius",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=20.9%2C53.9%2C26.8%2C56.4&layer=mapnik",
        "osmRelationId": "72596",
        "attractions": ["Vilnius óváros", "Trakai", "Kaunas", "Klaipėda", "Curonian Spit", "Keresztek hegye", "Gediminas-torony", "Užupis", "Palanga", "Aukštaitija Nemzeti Park"]
    },
    "LV": {
        "name": "Lettország",
        "flag": "🇱🇻",
        "officialFlag": "https://flagcdn.com/w320/lv.png",
        "code": "LV",
        "continent": "Európa",
        "callingCode": "+371",
        "area": "64,589 km²",
        "population": "1.9 millió",
        "language": "Lett",
        "capital": "Riga",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=20.9%2C55.7%2C28.2%2C58.1&layer=mapnik",
        "osmRelationId": "72594",
        "attractions": ["Riga óváros", "Sigulda", "Cēsis", "Jūrmala", "Rundāle kastély", "Gauja Nemzeti Park", "Kuldīga", "Liepāja", "Ventspils", "Turaida kastély"]
    },
    "EE": {
        "name": "Észtország",
        "flag": "🇪🇪",
        "officialFlag": "https://flagcdn.com/w320/ee.png",
        "code": "EE",
        "continent": "Európa",
        "callingCode": "+372",
        "area": "45,228 km²",
        "population": "1.3 millió",
        "language": "Észt",
        "capital": "Tallinn",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=21.8%2C57.5%2C28.2%2C59.7&layer=mapnik",
        "osmRelationId": "79510",
        "attractions": ["Tallinn óváros", "Tartu", "Saaremaa", "Lahemaa", "Pärnu", "Kadriorg palota", "Toompea-hegy", "Haapsalu", "Soomaa Nemzeti Park", "Narvai vár"]
    },
    "RU": {
        "name": "Oroszország",
        "flag": "🇷🇺",
        "officialFlag": "https://flagcdn.com/w320/ru.png",
        "code": "RU",
        "continent": "Európa",
        "callingCode": "+7",
        "area": "17,098,242 km²",
        "population": "146.2 millió",
        "language": "Orosz",
        "capital": "Moszkva",
        "currency": "Rubel (RUB)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=19.7%2C41.2%2C169.0%2C81.9&layer=mapnik",
        "osmRelationId": "60189",
        "attractions": ["Vörös tér", "Ermitázs", "Bajkál-tó", "Szibéria", "Szentpétervár", "Kreml", "Transzszibériai vasútvonal", "Kamcsatka", "Aranygyűrű városai", "Szocsi"]
    },
    "AD": {
        "name": "Andorra",
        "flag": "🇦🇩",
        "officialFlag": "https://flagcdn.com/w320/ad.png",
        "code": "AD",
        "continent": "Európa",
        "callingCode": "+376",
        "area": "468 km²",
        "population": "79,000",
        "language": "Katalán",
        "capital": "Andorra la Vella",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=1.4%2C42.4%2C1.8%2C42.7&layer=mapnik",
        "osmRelationId": "9407",
        "attractions": ["Caldea", "Casa de la Vall", "Grandvalira", "Soldeu", "Ordino", "Vallnord", "Madriu-Perafita-Claror völgy", "Sant Joan de Caselles templom", "Meritxell szentély", "Coma Pedrosa"]
    },
    "MC": {
        "name": "Monaco",
        "flag": "🇲🇨",
        "officialFlag": "https://flagcdn.com/w320/mc.png",
        "code": "MC",
        "continent": "Európa",
        "callingCode": "+377",
        "area": "2.02 km²",
        "population": "39,000",
        "language": "Francia",
        "capital": "Monaco",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=7.4%2C43.7%2C7.4%2C43.8&layer=mapnik",
        "osmRelationId": "1124039",
        "attractions": ["Monte Carlo kaszinó", "Monaco-Ville", "Herceg palota", "Oceanográfiai múzeum", "Formula 1 pálya", "Jardin Exotique", "Larvotto strand", "Szent Miklós-katedrális", "Port Hercules", "Japánkert"]
    },
    "SM": {
        "name": "San Marino",
        "flag": "🇸🇲",
        "officialFlag": "https://flagcdn.com/w320/sm.png",
        "code": "SM",
        "continent": "Európa",
        "callingCode": "+378",
        "area": "61 km²",
        "population": "34,000",
        "language": "Olasz",
        "capital": "San Marino",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=12.4%2C43.9%2C12.5%2C43.98&layer=mapnik",
        "osmRelationId": "54624",
        "attractions": ["Guaita torony", "Cesta torony", "Montale torony", "Palazzo Pubblico", "Basilica del Santo", "Piazza della Libertà", "Monte Titano", "Állami Múzeum", "Vámpírmúzeum", "Kínzómúzeum"]
    },
    "VA": {
        "name": "Vatikán",
        "flag": "🇻🇦",
        "officialFlag": "https://flagcdn.com/w320/va.png",
        "code": "VA",
        "continent": "Európa",
        "callingCode": "+39",
        "area": "0.17 km²",
        "population": "825",
        "language": "Latin, Olasz",
        "capital": "Vatikán",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=12.45%2C41.9%2C12.46%2C41.91&layer=mapnik",
        "osmRelationId": "36994",
        "attractions": ["Sixtus-kápolna", "Szent Péter bazilika", "Vatikáni múzeumok", "Apostoli palota", "Vatikáni kertek", "Szent Péter tér", "Vatikáni Grották", "Raffaello stanzái", "Laokoón-csoport", "Pápai Svájci Gárda"]
    },
    "LI": {
        "name": "Liechtenstein",
        "flag": "🇱🇮",
        "officialFlag": "https://flagcdn.com/w320/li.png",
        "code": "LI",
        "continent": "Európa",
        "callingCode": "+423",
        "area": "160 km²",
        "population": "38,000",
        "language": "Német",
        "capital": "Vaduz",
        "currency": "Svájci frank (CHF)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=9.47%2C47.05%2C9.64%2C47.27&layer=mapnik",
        "osmRelationId": "1155955",
        "attractions": ["Vaduz kastély", "Kunstmuseum", "Malbun", "Balzers", "Schaan", "Postamúzeum", "Gutenberg kastély", "Fürstensteig túraútvonal", "Rotes Haus", "Hofkellerei"],
        "alt_spellings": ["Liechtenstein", "LI", "Liechtenstein"]
    },
    "XK": {
        "name": "Koszovó",
        "flag": "🇽🇰",
        "officialFlag": "https://flagcdn.com/w320/xk.png",
        "code": "XK",
        "continent": "Európa",
        "callingCode": "+383",
        "area": "10,887 km²",
        "population": "1.9 millió",
        "language": "Albán, Szerb",
        "capital": "Pristina",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=20.0%2C41.8%2C21.8%2C43.3&layer=mapnik",
        "osmRelationId": "2088990",
        "attractions": ["Pristina", "Prizren", "Peja", "Gjakova", "Mitrovica", "Visoki Dečani kolostor", "Gračanica kolostor", "Rugova-kanyon", "Gazimestan", "Mirusha-vízesés"],
        "alt_spellings": ["Kosovo", "XK", "Koszovó"]
    },
    "FO": {
        "name": "Feröer-szigetek",
        "flag": "🇫🇴",
        "officialFlag": "https://flagcdn.com/w320/fo.png",
        "code": "FO",
        "continent": "Európa",
        "callingCode": "+298",
        "area": "1,393 km²",
        "population": "53,000",
        "language": "Feröeri, Dán",
        "capital": "Tórshavn",
        "currency": "Feröeri korona (DKK)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-7.7%2C61.4%2C-6.2%2C62.4&layer=mapnik",
        "osmRelationId": "5331415",
        "attractions": ["Tórshavn", "Gásadalur", "Mykines", "Saksun", "Kirkjubøur", "Múlafossur vízesés", "Tinganes", "Vestmanna madársziklák", "Kalsoy szigete", "Sørvágsvatn tó"],
        "alt_spellings": ["Faroe Islands", "Føroyar", "FO", "Feröer-szigetek"]
    },
    "GL": {
        "name": "Grönland",
        "flag": "🇬🇱",
        "officialFlag": "https://flagcdn.com/w320/gl.png",
        "code": "GL",
        "continent": "Európa",
        "callingCode": "+299",
        "area": "2,166,086 km²",
        "population": "56,000",
        "language": "Grönlandi, Dán",
        "capital": "Nuuk",
        "currency": "Dán korona (DKK)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-73.0%2C59.8%2C-11.3%2C83.6&layer=mapnik",
        "osmRelationId": "2184713",
        "attractions": ["Nuuk", "Ilulissat jégfjord", "Kangerlussuaq", "Tasiilaq", "Scoresby Sound", "Északi fény", "Disko-öböl", "Qaqortoq", "Viking romok", "Kutyaszánozás"],
        "alt_spellings": ["Greenland", "Kalaallit Nunaat", "GL", "Grönland"]
    },
    "JE": {
        "name": "Jersey",
        "flag": "🇯🇪",
        "officialFlag": "https://flagcdn.com/w320/je.png",
        "code": "JE",
        "continent": "Európa",
        "callingCode": "+44",
        "area": "116 km²",
        "population": "107,000",
        "language": "Angol, Francia",
        "capital": "Saint Helier",
        "currency": "Font sterling (GBP)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-2.3%2C49.1%2C-2.0%2C49.3&layer=mapnik",
        "osmRelationId": "367988",
        "attractions": ["Saint Helier", "Mont Orgueil kastély", "Jersey Zoo", "Corbière világítótorony", "Durrell Wildlife", "Jersey War Tunnels", "Elizabeth Castle", "St Brelade's Bay", "La Mare Wine Estate", "Plemont Bay"],
        "alt_spellings": ["Jersey", "JE", "Jersey"]
    },
    "GG": {
        "name": "Guernsey",
        "flag": "🇬🇬",
        "officialFlag": "https://flagcdn.com/w320/gg.png",
        "code": "GG",
        "continent": "Európa",
        "callingCode": "+44",
        "area": "78 km²",
        "population": "67,000",
        "language": "Angol, Francia",
        "capital": "Saint Peter Port",
        "currency": "Font sterling (GBP)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-2.7%2C49.4%2C-2.5%2C49.5&layer=mapnik",
        "osmRelationId": "363999",
        "attractions": ["Saint Peter Port", "Castle Cornet", "Hauteville House", "Little Chapel", "Cobo Bay", "Sark szigete", "German Occupation Museum", "Shell Beach (Herm)", "Candie Gardens", "Fort Grey"],
        "alt_spellings": ["Guernsey", "GG", "Guernsey"]
    },
    "IM": {
        "name": "Man-sziget",
        "flag": "🇮🇲",
        "officialFlag": "https://flagcdn.com/w320/im.png",
        "code": "IM",
        "continent": "Európa",
        "callingCode": "+44",
        "area": "572 km²",
        "population": "85,000",
        "language": "Angol, Manx",
        "capital": "Douglas",
        "currency": "Font sterling (GBP)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-4.8%2C54.0%2C-4.3%2C54.4&layer=mapnik",
        "osmRelationId": "62269",
        "attractions": ["Douglas", "TT pálya", "Snaefell", "Peel kastély", "Laxey kerék", "Castle Rushen", "Manx Electric Railway", "Calf of Man", "Port Erin", "Curraghs Wildlife Park"],
        "alt_spellings": ["Isle of Man", "IM", "Man-sziget"]
    },
    "GI": {
        "name": "Gibraltár",
        "flag": "🇬🇮",
        "officialFlag": "https://flagcdn.com/w320/gi.png",
        "code": "GI",
        "continent": "Európa",
        "callingCode": "+350",
        "area": "6.8 km²",
        "population": "34,000",
        "language": "Angol",
        "capital": "Gibraltár",
        "currency": "Gibraltári font (GIP)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-5.37%2C36.1%2C-5.33%2C36.16&layer=mapnik",
        "osmRelationId": "1278736",
        "attractions": ["Gibraltár sziklája", "Barbár majmok", "Europa Point", "Great Siege Tunnels", "Main Street", "St. Michael's Cave", "Skywalk", "Moorish Castle", "Gibraltári botanikus kert", "Catalan Bay"],
        "alt_spellings": ["Gibraltar", "GI", "Gibraltár"]
    },
    "AX": {
        "name": "Åland-szigetek",
        "flag": "🇦🇽",
        "officialFlag": "https://flagcdn.com/w320/ax.png",
        "code": "AX",
        "continent": "Európa",
        "callingCode": "+358",
        "area": "1,580 km²",
        "population": "30,000",
        "language": "Svéd",
        "capital": "Mariehamn",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=19.5%2C59.8%2C21.0%2C60.4&layer=mapnik",
        "osmRelationId": "16513",
        "attractions": ["Mariehamn", "Kastelholm kastély", "Bomarsund", "Eckerö", "Kökar", "Pommern múzeumhajó", "Jan Karlsgården szabadtéri múzeum", "Getabergen", "Kobba Klintar", "Ålandi Tengerészeti Múzeum"],
        "alt_spellings": ["Åland Islands", "AX", "Åland-szigetek"]
    },
    "SJ": {
        "name": "Svalbard",
        "flag": "🇸🇯",
        "officialFlag": "https://flagcdn.com/w320/sj.png",
        "code": "SJ",
        "continent": "Európa",
        "callingCode": "+47",
        "area": "61,022 km²",
        "population": "2,700",
        "language": "Norvég",
        "capital": "Longyearbyen",
        "currency": "Norvég korona (NOK)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=10.0%2C76.0%2C35.0%2C81.0&layer=mapnik",
        "osmRelationId": "1404829",
        "attractions": ["Longyearbyen", "Barentsburg", "Ny-Ålesund", "Jegesmedve szafari", "Északi fény", "Magbank (Global Seed Vault)", "Jégbarlangok", "Pyramiden", "Hajókirándulás a gleccserekhez", "Svalbard Múzeum"],
        "alt_spellings": ["Svalbard", "SJ", "Svalbard"]
    },
    "GR": {
        "name": "Görögország",
        "flag": "🇬🇷",
        "officialFlag": "https://flagcdn.com/w320/gr.png",
        "code": "GR",
        "continent": "Európa",
        "callingCode": "+30",
        "area": "131,957 km²",
        "population": "10.7 millió",
        "language": "Görög",
        "capital": "Athén",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=19.4%2C34.8%2C28.2%2C41.7&layer=mapnik",
        "osmRelationId": "192307",
        "attractions": ["Akropolisz", "Santorini", "Mykonos", "Delphi", "Meteora", "Kréta", "Rodosz", "Korfu", "Olympia", "Navagio-öböl (Zakynthos)"],
        "alt_spellings": ["Greece", "Hellas", "GR", "Görögország"]
    },
    "CY": {
        "name": "Ciprus",
        "flag": "🇨🇾",
        "officialFlag": "https://flagcdn.com/w320/cy.png",
        "code": "CY",
        "continent": "Európa",
        "callingCode": "+357",
        "area": "9,251 km²",
        "population": "1.2 millió",
        "language": "Görög, Török",
        "capital": "Nicosia",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=32.3%2C34.6%2C34.6%2C35.7&layer=mapnik",
        "osmRelationId": "363997",
        "attractions": ["Paphos", "Limassol", "Troodos hegység", "Kyrenia", "Larnaca", "Nissi Beach (Ayia Napa)", "Királysírok", "Aphrodité sziklája", "Famagusta", "Zöld vonal (Nicosia)"],
        "alt_spellings": ["Cyprus", "Kıbrıs", "CY", "Ciprus"]
    },
    "MT": {
        "name": "Málta",
        "flag": "🇲🇹",
        "officialFlag": "https://flagcdn.com/w320/mt.png",
        "code": "MT",
        "continent": "Európa",
        "callingCode": "+356",
        "area": "316 km²",
        "population": "514,000",
        "language": "Máltai, Angol",
        "capital": "Valletta",
        "currency": "Euró (EUR)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=14.2%2C35.8%2C14.6%2C36.1&layer=mapnik",
        "osmRelationId": "365307",
        "attractions": ["Valletta", "Mdina", "Blue Lagoon", "Gozo", "Hypogeum", "Szent János-társkatedrális", "Popeye falu", "Hagar Qim templomok", "Három Város", "Dingli sziklák"],
        "alt_spellings": ["Malta", "MT", "Málta"]
    },
    "AL": {
        "name": "Albánia",
        "flag": "🇦🇱",
        "officialFlag": "https://flagcdn.com/w320/al.png",
        "code": "AL",
        "continent": "Európa",
        "callingCode": "+355",    
        "area": "28,748 km²",    
        "population": "2.8 millió",    
        "language": "Albán",    
        "capital": "Tirana",    
        "currency": "Lek (ALL)",    
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=19.3%2C39.6%2C21.1%2C42.7&layer=mapnik",    
        "osmRelationId": "72277",    
        "attractions": ["Tirana", "Berat", "Gjirokastër", "Saranda", "Shkodër", "Butrint", "Albán Riviéra", "Koman-tó", "Theth Nemzeti Park", "Apollonia"],    
        "alt_spellings": ["Albania", "AL", "Albánia"]
    },
    "MK": {
        "name": "Macedonia",
        "flag": "🇲🇰",
        "officialFlag": "https://flagcdn.com/w320/mk.png",
        "code": "MK",
        "continent": "Európa",
        "callingCode": "+389",
        "area": "257,102 km²",
        "population": "2.1 millió",
        "language": "Macedon",
        "capital": "Skopje",
        "currency": "Macedón denár (MKD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=20.5%2C40.9%2C23.0%2C42.4&layer=mapnik",
        "osmRelationId": "53293",        
        "attractions": ["Ohrid", "Skopje", "Bitola", "Prilep", "Mavrovo", "Matka-kanyon", "Szent Naum kolostor", "Heraclea Lyncestis", "Galičica Nemzeti Park", "Kamen Kukli"],
        "alt_spellings": ["Macedonia", "MK", "Macedoniasz"]
    },
    "RS": {
        "name": "Szerbia",
        "flag": "🇷🇸",
        "officialFlag": "https://flagcdn.com/w320/rs.png",
        "code": "RS",
        "continent": "Európa",
        "callingCode": "+381",
        "area": "88,361 km²",
        "population": "6.7 millió",
        "language": "Szerb",
        "capital": "Belgrade",
        "currency": "Szerb dinár (RSD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=18.8%2C42.2%2C23.0%2C46.2&layer=mapnik",
        "osmRelationId": "186385",
        "attractions": ["Belgrade", "Novi Sad", "Niš", "Đavolja Varoš", "Studenica kolostor", "Tara Nemzeti Park", "Kalemegdan erőd", "Szent Száva-templom", "Uvac kanyon", "Oplenac"],
        "alt_spellings": ["Serbia", "RS", "Szerbia"]
    },
    "TR": {
        "name": "Törökország",
        "flag": "🇹🇷",
        "officialFlag": "https://flagcdn.com/w320/tr.png",
        "code": "TR",
        "continent": "Európa",
        "callingCode": "+90",
        "area": "783,562 km²",
        "population": "83.4 milliom",
        "language": "Türk",
        "capital": "Ankara",
        "currency": "Türk lirası (TRY)",    
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=27.2%2C38.6%2C42.5%2C42.5&layer=mapnik",    
        "osmRelationId": "145",    
        "attractions": ["Istanbul", "Kappadókia", "Pamukkale", "Ephesus", "Antalya", "Göbekli Tepe", "Troy", "Mount Ararat", "Topkapi palota", "Bodrum"],    
        "alt_spellings": ["Turkey", "Türkiye", "TR", "Türkisz"]    
    }
}