const Oceánia = {
     "AU": {
        "name": "Ausztrália",
        "flag": "🇦🇺",
        "officialFlag": "https://flagcdn.com/w320/au.png",
        "code": "AU",
        "continent": "Óceánia",
        "callingCode": "+61",
        "area": "7,692,024 km²",
        "population": "25.7 millió",
        "language": "Angol",
        "capital": "Canberra",
        "currency": "Ausztrál dollár (AUD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=113.3%2C-43.6%2C153.6%2C-10.7&layer=mapnik",
        "osmRelationId": "80500",
        "attractions": ["Sydney Opera House", "Uluru", "Great Barrier Reef", "Melbourne", "Kakadu", "Great Ocean Road", "Kék-hegység", "Tasmánia", "Whitsunday-szigetek", "Daintree esőerdő"]
    },
    "NZ": {
        "name": "Új-Zéland",
        "flag": "🇳🇿",
        "officialFlag": "https://flagcdn.com/w320/nz.png",
        "code": "NZ",
        "continent": "Óceánia",
        "callingCode": "+64",
        "area": "268,021 km²",
        "population": "5.1 millió",
        "language": "Angol, Maori",
        "capital": "Wellington",
        "currency": "Új-zélandi dollár (NZD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=166.5%2C-47.3%2C178.6%2C-34.4&layer=mapnik",
        "osmRelationId": "57566",
        "attractions": ["Milford Sound", "Queenstown", "Rotorua", "Bay of Islands", "Franz Josef gleccser", "Hobbiton", "Tongariro Nemzeti Park", "Waitomo-barlangok", "Abel Tasman Nemzeti Park", "Aoraki / Mount Cook"]
    },
    "PG": {
        "name": "Pápua Új-Guinea",
        "flag": "🇵🇬",
        "officialFlag": "https://flagcdn.com/w320/pg.png",
        "code": "PG",
        "continent": "Óceánia",
        "callingCode": "+675",
        "area": "462,840 km²",
        "population": "9.1 millió",
        "language": "Angol, Tok Pisin, Hiri Motu",
        "capital": "Port Moresby",
        "currency": "Kina (PGK)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=140.8%2C-11.7%2C159.0%2C-1.3&layer=mapnik",
        "osmRelationId": "311396",
        "attractions": ["Kokoda Track", "Mount Wilhelm", "Sepik folyó", "Rabaul", "Trobriand szigetek", "Goroka Show", "Mount Hagen", "Alotau", "Madang", "New Ireland"]
    },
    "FJ": {
        "name": "Fidzsi",
        "flag": "🇫🇯",
        "officialFlag": "https://flagcdn.com/w320/fj.png",
        "code": "FJ",
        "continent": "Óceánia",
        "callingCode": "+679",
        "area": "18,274 km²",
        "population": "896,000",
        "language": "Angol, Fidzsi, Hindi",
        "capital": "Suva",
        "currency": "Fidzsi dollár (FJD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=177.0%2C-20.7%2C-178.1%2C-12.5&layer=mapnik",
        "osmRelationId": "571747",
        "attractions": ["Coral Coast", "Mamanuca szigetek", "Yasawa szigetek", "Suva", "Pacific Harbour", "Taveuni", "Garden of the Sleeping Giant", "Sawa-i-Lau barlangok", "Bouma Nemzeti Park", "Denarau-sziget"]
    },
    "WS": {
        "name": "Szamoa",
        "flag": "🇼🇸",
        "officialFlag": "https://flagcdn.com/w320/ws.png",
        "code": "WS",
        "continent": "Óceánia",
        "callingCode": "+685",
        "area": "2,842 km²",
        "population": "198,000",
        "language": "Szamoai, Angol",
        "capital": "Apia",
        "currency": "Tala (WST)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-172.8%2C-14.1%2C-171.4%2C-13.4&layer=mapnik",
        "osmRelationId": "571749",
        "attractions": ["To Sua Ocean Trench", "Lalomanu Beach", "Piula Cave Pool", "Apia", "Savai'i sziget", "Alofaaga Blowholes", "Papaseea Sliding Rocks", "Robert Louis Stevenson Múzeum", "Falealupo Canopy Walk", "Saleaula lávamező"]
    },
    "TO": {
        "name": "Tonga",
        "flag": "🇹🇴",
        "officialFlag": "https://flagcdn.com/w320/to.png",
        "code": "TO",
        "continent": "Óceánia",
        "callingCode": "+676",
        "area": "747 km²",
        "population": "105,000",
        "language": "Tongai, Angol",
        "capital": "Nuku'alofa",
        "currency": "Pa'anga (TOP)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-175.7%2C-21.5%2C-173.9%2C-15.6&layer=mapnik",
        "osmRelationId": "218663",
        "attractions": ["Ha'amonga 'a Maui", "Blowholes", "Fafa sziget", "Nuku'alofa", "Vava'u szigetek", "Anahulu-barlang", "Swallows-barlang", "Eua Nemzeti Park", "Hosszúszárnyú bálnák megfigyelése", "Pangaimotu-sziget"]
    },
    "VU": {
        "name": "Vanuatu",
        "flag": "🇻🇺",
        "officialFlag": "https://flagcdn.com/w320/vu.png",
        "code": "VU",
        "continent": "Óceánia",
        "callingCode": "+678",
        "area": "12,189 km²",
        "population": "307,000",
        "language": "Bislama, Angol, Francia",
        "capital": "Port Vila",
        "currency": "Vatu (VUV)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=166.5%2C-20.2%2C170.2%2C-13.1&layer=mapnik",
        "osmRelationId": "218443",
        "attractions": ["Mount Yasur", "Champagne Beach", "Blue Holes", "Port Vila", "Tanna sziget", "Millennium-barlang", "Land Diving (Pünkösd-sziget)", "Hideaway-sziget", "Mele Cascades", "Espiritu Santo"]
    },
    "PW": {
        "name": "Palau",
        "flag": "🇵🇼",
        "officialFlag": "https://flagcdn.com/w320/pw.png",
        "code": "PW",
        "continent": "Óceánia",
        "callingCode": "+680",
        "area": "459 km²",
        "population": "18,000",
        "language": "Palaui, Angol",
        "capital": "Ngerulmud",
        "currency": "Dollár (USD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=134.1%2C2.9%2C134.7%2C8.1&layer=mapnik",
        "osmRelationId": "571805",
        "attractions": ["Rock Islands", "Jellyfish Lake", "Blue Corner", "German Channel", "Koror", "Ngardmau-vízesés", "Peleliu", "Belau Nemzeti Múzeum", "Milky Way", "Badrulchau kőmonolitok"]
    },
    "MH": {
        "name": "Marshall-szigetek",
        "flag": "🇲🇭",
        "officialFlag": "https://flagcdn.com/w320/mh.png",
        "code": "MH",
        "continent": "Óceánia",
        "callingCode": "+692",
        "area": "181 km²",
        "population": "59,000",
        "language": "Marshall, Angol",
        "capital": "Majuro",
        "currency": "Dollár (USD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=165.0%2C4.6%2C171.9%2C14.8&layer=mapnik",
        "osmRelationId": "571771",
        "attractions": ["Bikini Atoll", "Majuro", "Kwajalein", "Arno Atoll", "Laura Beach", "Enewetak Atoll", "Alele Múzeum", "Rongelap Atoll", "Kalalin Pass", "Bokolap-sziget"]
    },
    "FM": {
        "name": "Mikronézia",
        "flag": "🇫🇲",
        "officialFlag": "https://flagcdn.com/w320/fm.png",
        "code": "FM",
        "continent": "Óceánia",
        "callingCode": "+691",
        "area": "702 km²",
        "population": "115,000",
        "language": "Angol",
        "capital": "Palikir",
        "currency": "Dollár (USD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=137.4%2C1.0%2C163.0%2C10.1&layer=mapnik",
        "osmRelationId": "571891",
        "attractions": ["Chuuk Lagoon", "Nan Madol", "Palikir", "Kosrae", "Pohnpei", "Yap", "Lelu romok", "Kepirohi-vízesés", "Fekete korallok (Black Coral)", "Ant Atoll"]
    },
    "NR": {
        "name": "Nauru",
        "flag": "🇳🇷",
        "officialFlag": "https://flagcdn.com/w320/nr.png",
        "code": "NR",
        "continent": "Óceánia",
        "callingCode": "+674",
        "area": "21 km²",
        "population": "10,800",
        "language": "Naurui, Angol",
        "capital": "Yaren",
        "currency": "Ausztrál dollár (AUD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=166.9%2C-0.6%2C166.96%2C-0.5&layer=mapnik",
        "osmRelationId": "571804",
        "attractions": ["Command Ridge", "Anibare Bay", "Buada Lagoon", "Yaren", "Moqua Caves", "Nauru Múzeum", "Japán ágyúk", "Foszfátbányászat maradványai", "Cantilever", "Anibare kikötő"]
    },
    "KI": {
        "name": "Kiribati",
        "flag": "🇰🇮",
        "officialFlag": "https://flagcdn.com/w320/ki.png",
        "code": "KI",
        "continent": "Óceánia",
        "callingCode": "+686",
        "area": "811 km²",
        "population": "119,000",
        "language": "Gilberti, Angol",
        "capital": "Tarawa",
        "currency": "Ausztrál dollár (AUD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=-174.0%2C-11.4%2C-150.2%2C4.7&layer=mapnik",
        "osmRelationId": "571178",
        "attractions": ["Christmas Island", "Tarawa", "Kiritimati", "Phoenix Islands", "Line Islands", "Betio", "Ambo", "Fanning-atoll (Tabuaeran)", "Abaiang", "Butaritari"]
    },
    "TV": {
        "name": "Tuvalu",
        "flag": "🇹🇻",
        "officialFlag": "https://flagcdn.com/w320/tv.png",
        "code": "TV",
        "continent": "Óceánia",
        "callingCode": "+688",
        "area": "26 km²",
        "population": "11,800",
        "language": "Tuvalui, Angol",
        "capital": "Funafuti",
        "currency": "Ausztrál dollár (AUD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=176.1%2C-10.8%2C179.9%2C-5.6&layer=mapnik",
        "osmRelationId": "921473",
        "attractions": ["Funafuti Atoll", "Nanumea", "Nukufetau", "Vaitupu", "Nui", "Funafuti Természetvédelmi Terület", "Tuvalu Philatelic Bureau", "Repülőtér (közösségi tér)", "Vaiaku Lagi Hotel", "Tepuka Islet"]
    },
    "SB": {
        "name": "Salamon-szigetek",
        "flag": "🇸🇧",
        "officialFlag": "https://flagcdn.com/w320/sb.png",
        "code": "SB",
        "continent": "Óceánia",
        "callingCode": "+677",
        "area": "28,896 km²",
        "population": "687,000",
        "language": "Angol",
        "capital": "Honiara",
        "currency": "Salamon dollár (SBD)",
        "mapUrl": "https://www.openstreetmap.org/export/embed.html?bbox=155.5%2C-12.3%2C170.2%2C-5.1&layer=mapnik",
        "osmRelationId": "219939",
        "attractions": ["Guadalcanal", "Malaita", "Western Province", "Honiara", "Rennell Island", "Marovo Lagoon", "Gizo", "Kennedy-sziget", "Mataniko-vízesés", "Tenaru-vízesés"]
    }
}